[#introduction]
== Introduction

////
   This document presents a technique for using a Markdown [Markdown]
   syntax variant, called Pandoc [Pandoc], and a bit of XML [RFC2629] as
   a source format for documents that are Internet-Drafts (I-Ds) or
   RFCs.

   The goal of this technique is to let an author of an I-D focus on the
   main body of text without being distracted too much by XML tags;
   however, it does not alleviate the need to typeset some files in XML.

   Pandoc is a format that is almost plain text and therefore
   particularly well suited for editing RFC-like documents.  The syntax
   itself is a superset of the syntax championed by Markdown.




   Mmark [mmark] is a markdown processor.  It supports the markdown
   syntax and has been extended with (syntax) features found in other
   markdown implementations like kramdown [2], PHP markdown extra [3],
   [pandoc], leanpub [4] and even asciidoc [5].  This allows mmark to be
   used to write larger, structured documents such as RFC and I-Ds or
   even books, while not deviating too far from markdown.

   Mmark is a fork of blackfriday [blackfriday] and is written in Golang
   and very fast.  Input to mmark must be UTF-8, the output is also UTF-
   8.  Mmark converts tabs to 4 spaces.

   The goals of mmark are:

   (I)     Self contained: a single file can be converted to XML2RFC v2
           or (v3) or HTML5.

   (II)    Make the markdown "source code" look as natural as possible.

   (III)   Provide seemless upgrade path to XML2RFC v3.

   Mmark uses two scans when converting a document and does not build an
   internal AST of the document, this means it can not adhere 100% to
   the CommonMark [6] specification, however the CommonMark test suite
   is used when developing mmark.  Currently mmark passes ~60% of the
   tests.

   Using Figure 1 from [RFC7328], mmark can be positioned as follows:

    +-------------------+   pandoc   +---------+
    | ALMOST PLAIN TEXT |   ------>  | DOCBOOK |
    +-------------------+            +---------+
                  |      \                 |
    non-existent  |       \_________       | xsltproc
      faster way  |        *mmark*  \      |
                  v                  v     v
          +------------+    xml2rfc  +---------+
          | PLAIN TEXT |  <--------  |   XML   |
          +------------+             +---------+

                                 Figure 1

   Note that kramdown-2629 [7] fills the same niche as mmark.







   Internet Drafts and RFCs are predominantly written in embedded-text,
   compile-based formatting systems [1][4][5].  The primary and first
   such system is NROFF, a text-formatting utility based on manual entry
   of embedded configuration commands, such as ".p" for new paragraphs.
   XML is a more recent alternative that uses structure tags instead of
   explicit formatting commands to allow a single file (.xml) to be
   'compiled' into ASCII output, HTML, or a variety of other formats as
   desired [7].

   Although XML adds more modern semantic information to the structure
   tags, neither system supports modern WYSIWYG (what-you-see-is-what-
   you-get) editing.  Editors such as Microsoft Word and Corel
   WordPerfect provide not only WYSIWYG editing, but also semantic tags
   as well as outline-mode capabilities.  To that end, a Word template
   called 2-Word.template.rtf was created that supports authoring RFCs,
   as described in RFC 3285 [6].  That version succeeded in enabling
   Word-based RFC editing, but did not support Word's outline mode
   renumbering capabilities.

   This document describes the properties and use of a revised Microsoft
   Word template (.dot) file that supports Internet Draft and RFC
   formatting, intended as an update to that of RFC 3285.  This version,
   called 2-Word-v2.0.template.dot, addresses a number of issues with
   the preliminary version:

   o  redefines basic styles (Normal, Heading1, etc.) rather than
      creating new styles,

   o  updates the boilerplate according to BCP 78,

   o  uses more conventional methods for autonumbered references and
      figures, including support for name-based references (e.g.,
      "[Tou2005]"), and

   o  supports direct output to a printer from the .doc source, as well
      as RFC-3285-style 'print to text' with post-processing on Windows-
      based PCs.

   This document assumes familiarity with Microsoft Windows operating
   systems and the Word application.
////