
== Document Structure And Asciidoctor Syntax

Asciidoctor syntax is presented in the Asciidoctor user manual
<<Asciidoctor-Manual>>.  AsciiRFC is a subset of Asciidoctor syntax,
with the addition of bibliographic macros
(<<asciidoctor_bibliography>>).

Asciidoctor syntax consists of:

* A document header, containing a title, a list of authors, and
document attributes in lines prefixed with `:`.

* An optional document preamble, separated from the document header by a
blank line, and not containing any section titles.

* A number of sections, set off by a section title (a line prefixed
with two or more `=`.)

A section may contain:

* Other sections, whose level of nesting is indicated by the number of
`=` in their header.

* Blocks of text. Blocks can have metadata (including a title, an
anchor for cross-references, and attributes.)

Blocks can be:

* Paragraphs, which are terminated by blank lines.

* Lists. List items are by default paragraphs, but can span over
multiple paragraphs.

* Delimited blocks (with a line delimiter on either side of them);
these include tables, notes, sidebars, source code, block quotes,
examples, and unprocessed content (e.g. raw XML). Delimited blocks
contain by default one or more paragraphs.

* List items can contain other blocks, including both nested lists and
delimited blocks.

* Some delimited blocks can contain other delimited blocks; for
example, examples can contain source code as well as discussion in
paragraphs.

* Blocks of text consist of inline text, which itself can contain
markup.


Inline markup includes:

* Text formatting: bold, italic, superscript, subscript, monospace.

* Custom markup macros. (AsciiRFC uses two: `bcp14, comment`.)

* URLs, including display text to render.

* Inline anchors.

* Cross-references to anchors (IDs of blocks or spans of text),
including display text to render.

* Images, audio, and visual files. (AsciiRFC only supports images.)

* Index terms.

* Equations (native support for <<AsciiMathML>> and <<TeX-LaTeX>>, via
the <<MathJax>> tool). (Not supported in AsciiRFC, since there is no
RFC XML equivalent.)

* Footnotes. (Not supported in AsciiRFC.)


=== AsciiRFC Mapping To Asciidoctor syntax

The Asciidoctor syntax document structure aligns with both the RFC XML v2
and the RFC XML v3 structure.  In the following, RFC XML v3 equivalences are given
to the basic Asciidoctor structure.

Header::
  `<rfc>` attributes, most `front` elements.

Preamble::
  `front/abstract` and `front/note`.

Sections::
  `middle/section` elements.

Sections with `bibliography` style attribute::
  `back/references` elements.

Sections with `appendix` style attribute::
  `back/section` elements.

Paragraphs::
  `t` elements.

Lists::
  `ul`, `ol`, `dl` elements.

Delimited blocks::
  `artwork`, `aside`, `blockquote`, `figure`, `note`, `sourcecode`, `table`.

Inline markup::
  `bcp14`, `br`, `cref`, `em`, `eref`, `iref`, `relref`, `strong`, `sub`,
  `sup`, `tt`, `xref`.

Full details of the mapping of AsciiRFC elements to RFC XML v2 and v3
elements, and of how to convert AsciiRFC documents to RFC XML, are
given in the documentation of <<asciidoctor-rfc>>.


=== Simple Illustration

This section gives an overview of how to create an RFC XML document in
AsciiRFC, with some pitfalls to be aware of.

Illustrations are in RFC XML v3 and RFC XML v2.

A sample AsciiRFC document is provided in <<source-sample-asciirfc>>,
together with its corresponding rendering in:

* RFC XML v3 (<<source-sample-asciirfc-output-v3>>)

* RFC XML v2 (<<source-sample-asciirfc-output-v2>>)

[[source-sample-asciirfc]]
.Sample Internet-Draft in AsciiRFC
====
[source,asciidoc]
--------
<CODE BEGINS>
include::../examples/rfc-asciirfc-template/draft-asciirfc-template.adoc[lines=1..33]
include::../examples/rfc-asciirfc-template/sections/00-abstract.adoc[]
include::../examples/rfc-asciirfc-template/sections/01-intro.adoc[]
include::../examples/rfc-asciirfc-template/sections/02-conventions.adoc[]
include::../examples/rfc-asciirfc-template/sections/03-symbols.adoc[]
include::../examples/rfc-asciirfc-template/sections/10-security.adoc[]
include::../examples/rfc-asciirfc-template/sections/11-iana.adoc[]
include::../examples/rfc-asciirfc-template/sections/98-references.adoc[]
include::../examples/rfc-asciirfc-template/sections/97-examples.adoc[]
include::../examples/rfc-asciirfc-template/sections/99-acknowledgements.adoc[]
<CODE ENDS>
--------
====

The first block of text, from
`= Template For Writing An Internet-Draft In AsciiRFC` through to
`:country_2: United States of America`, is
the document header. It contains a title in the first line, an author
attribution (`Josiah Carberry; Thomas Kandell`), and then a set of
document attributes, conveying
information about the document as well as information about its
authors. This information ends up in RFC XML either as attributes of the root
`rfc` tag, elements of the `front` tag, or processing instructions.

The following blocks of text, up until the first section header
(`== Introduction`), are the document preamble. They are
treated by the document converter as containing the document abstract
(`abstract`), followed by any notes if present.

[subs="quotes"]
Section headers delimit the sections of the main body of the document,
starting with `== Introduction`. The document converter treats the first section
of the document as the start of the `middle` section in RFC XML.
The first section header is followed by a paragraph, and other
sections and paragraphs. The number of `=` signs can be one higher than that of
the preceding section header, which indicates that they are subsections
of that section; so `=== Operators`
is a subsection of the preceding `== Symbols And Abbreviations`.

The paragraphs contain some inline formatting
(e.g. boldface: `\*MUST*`, monospace: `{backtick}type{backtick}`), and sections can
also contain blocks other than normal paragraphs; the section
`== Operators`, for example, contains
a definition list (whose terms are delimited by `::`), and the
subsection `=== Example 1` contains a code snippet
(delimited by `----`, and tagged with the style attribute `[source,json]`,
indicating that this is a JSON sourcecode listing). The document
can also include comments (`//` for inline, `////` for blocks),
which are not rendered when the document is processed.

[subs="quotes"]
The introductory section in this example
contains a citation of a reference, which in this
version of AsciiRFC is treated identically to a cross-reference
(`<<RFC7253>>`) -- the crossreference being to the references
section of the document. Sections and blocks of texts within the
document can also be the target of crossreferences; for example,
the section header `=== Operators`
is preceded by the anchor `[#operators]`, and that anchor
is already referenced in the section `== Security Considerations`.

The third last and second last section are tagged with the style attribute
`[bibliography]`, which identifies them as references containers; the
document converter accordingly inserts them into the `back` element under
RFC XML. The contents of the references sections are in this
instance raw XML, delimited as a passthrough block (with
`{fourpluses}`), which the converter does not alter.

The final section is tagged with the style attribute `[appendix]`,
and is treated as such.

The RFC XML v3 document generated from this AsciiRFC document is:

[[source-sample-asciirfc-output-v3]]
.Sample Internet-Draft In AsciiRFC, Output In RFC XML v3 Format
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-asciirfc-template/xml3/draft-asciirfc-template.xml[]
<CODE ENDS>
----
====

Some default processing instructions have already been prefixed to the
XML.

Our AsciiRFC converter can also generate RFC XML v2 from the same
source AsciiRFC, as shown in <<source-sample-asciirfc-output-v2>>.
Output in RFC XML v2 is not extensively described in this document.

[[source-sample-asciirfc-output-v2]]
.Sample Internet-Draft In AsciiRFC, Output In RFC XML v2 Format
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-asciirfc-template/xml2/draft-asciirfc-template.xml[]
<CODE ENDS>
----
====

