
== Document Structure And Asciidoctor Syntax

Asciidoctor syntax is presented in the Asciidoctor user manual
<<Asciidoctor-Manual>>.  AsciiRFC is a subset of Asciidoctor syntax,
with the addition of bibliographic macros
(<<asciidoctor_bibliography>>).

Asciidoctor syntax consists of:

* A document header, containing a title, a list of authors, and
document attributes in lines prefixed with `:`.

* An optional document preamble, separated from document header by a
blank line.

* A number of sections, set off by a section title (a line prefixed
with two or more `=`. 

A section may contain:

* Other sections, whose level of nesting is indicated by the number of
`=` in their header.

* Blocks of text. Blocks can have metadata (including a title, an
anchor for cross-references, and attributes.) 

Blocks can be:

* Paragraphs, which are terminated by blank lines.

* Lists. List items are by default paragraphs, but can span over
multiple paragraphs.

* Delimited blocks (with a line delimiter on either side of them);
these include tables, notes, sidebars, source code, block quotes,
examples, and unprocessed content (e.g. raw XML). Delimited blocks
contain by default one or more paragraphs.

* List items can contain other blocks, including both nested lists and
delimited blocks.

* Some delimited blocks can contain other delimited blocks; for
example, examples can contain source code as well as discussion in
paragraphs.

* Blocks of text consist of inline text, which themselves can contain
markup.


Inline markup includes:

* Text formatting: bold, italic, superscript, subscript, monospace.

* Custom markup macros. (AsciiRFC uses one: `bcp14`.)

* URLs, including display text.

* Inline anchors.

* Cross-references to anchors (IDs of blocks or spans of text),
including display text.

* Images, audio, and visual files. (AsciiRFC only supports images.)

* Index terms.

* Equations (native support for <<AsciiMathML>> and <<TeX-LaTeX>>, via
the <<MathJax>> tool). (Not supported in AsciiRFC, since there is no
RFC XML equivalent.)

* Footnotes. (Not supported in AsciiRFC.)


=== AsciiRFC Mapping To Asciidoctor syntax

The Asciidoctor syntax document structure aligns with the RFC XML v2
and v3 structure.  In the following, v3 equivalences are given.

Header::
  `<rfc>` attributes, most `front` elements.

Preamble::
  `front/abstract` and `front/note`.

Sections::
  `middle/section` elements.

Sections with `bibliography` style attributes::
  `back/references` elements.

Sections with `appendix` style attributes::
  `back/section` elements.

Paragraphs::
  `t` elements.

Lists::
  `ul`, `ol`, `dl` elements.

Delimited blocks::
  `artwork`, `aside`, `blockquote`, `figure`, `note`, `sourcecode`, `table`.

Inline markup::
  `bcp14`, `br`, `cref`, `em`, `eref`, `iref`, `relref`, `strong`, `sub`,
  `sup`, `tt`, `xref`.

Full details of the mapping of AsciiRFC elements to RFC XML v2 and v3
elements, and of how to convert AsciiRFC documents to RFC XML, are
given in the documentation of <<asciidoctor-rfc>>.


=== Simple Illustration

This section gives an overview of how to create an RFC XML document in
AsciiRFC, with some pitfalls to be aware of.

Illustrations are in RFC XML v3 and RFC XML v2.

A sample AsciiRFC document is provided in <<source-sample-asciirfc>>,
and its corresponding rendering in:

* RFC XML v3 (<<source-sample-asciirfc-output-v3>>)

* RFC XML v2 (<<source-sample-asciirfc-output-v2>>)

[[source-sample-asciirfc]]
.Sample Internet-Draft in AsciiRFC
====
[source,asciidoc]
----
<CODE BEGINS>
include::examples/draft-divination-cfapi.adoc[]
<CODE ENDS>
----
====

The first block of text, from 
`= An API For Calendar-Based Fortune Heuristics Services` through to
`:country_2: USA`, is
the document header. It contains a title in the first line, an author
attribution, and then a set of document attributes, conveying
information about the document as well as information about its
authors. This information ends up either as attributes of the root
`rfc` tag, elements of the `front` tag, or processing instructions.

The following blocks of text, up until the first section header 
(`== Claim: Michael Palin`), are the document preamble. They are
treated by the document converter as containing the document abstract
(`abstract`), followed by any notes (`note`, identified above by the
`NOTE:` heading).

[subs="quotes"]
The first section header (`== Claim: Michael Palin`) is preceded by an
anchor for that section (`[#michaelpalin]`). There is a
cross-reference to that anchor already in place in the abstract
(`<<michaelpalin>>`). The document converter treats the first section
of the document as the start of the `middle` section of the document.

[subs="quotes"]
The first section header is followed by a paragraph, and other
sections and paragraphs. The number of `=` signs are one higher than
the initial section header, which indicates that they are subsections
of that section. The paragraphs contains some inline formatting
(italics: `\_pause for laughter_`; boldface: `\*lick*`). The first
paragraph also contains a citation of a reference, which in this
version of AsciiRFC is treated identically to a cross-reference
(`<<RFC7253>>`). (If the bibliography preprocessor were used, it would
be encoded differently.)

The second last section is tagged with the style attribute
`[bibliography]`, which identifies it as a references container; the
document converter accordingly inserts this into the `back` element of
the document. The contents of the references section are in this
instance raw XML, delimited as a passthrough block (with
`{fourpluses}`), which the converter does not alter.  The final
section is tagged with the style attribute `[appendix]`, and is
treated as such.

The RFC XML v3 document generated from this AsciiRFC document is:

[[source-sample-asciirfc-output-v3]]
.Sample Internet-Draft In AsciiRFC, Output In RFC XML v3 Format
====
[source,xml]
----
<CODE BEGINS>
include::examples/draft-divination-cfapi.xml3[]
<CODE ENDS>
----
====

Some default processing instructions have already been prefixed to the
XML.

Our AsciiRFC converter can also generate RFC XML v2 from the same
source AsciiRFC, as shown in <<source-sample-asciirfc-output-v2>>.
Output in RFC XML v2 is not extensively described in this document.

[[source-sample-asciirfc-output-v2]]
.Sample Internet-Draft In AsciiRFC, Output In RFC XML v2 Format
====
[source,xml]
----
<CODE BEGINS>
include::examples/draft-divination-cfapi.xml[]
<CODE ENDS>
----
====

