
== Document Structure And AsciiDoctor Syntax

The syntax of Asciidoctor is presented in the
http://asciidoctor.org/docs/user-manual/#compared-to-markdown[Asciidoctor user manual].

Asciidoctor consists of:

* A document header, containing a title, a list of authors, and document
attributes in lines prefixed with `:`.

* An optional document preamble, separated from document header by a blank line.

* A number of sections, set off by a section title (a line prefixed with two or
more `=`. A section may contain:

** Other sections, whose level of nesting is indicated by the number of `=` in
their header.

** Blocks of text. Blocks can have metadata (including a title, an anchor for
cross-references, and attributes.) Blocks can be:

*** Paragraphs, which are terminated by blank lines.

*** Lists. List items are by default paragraphs, but can span over multiple
paragraphs.

*** Delimited blocks (with a line delimiter on either side of them); these
include tables, notes, sidebars, source code, block quotes, examples, and
unprocessed content (e.g. raw XML). Delimited blocks contain by default one or
more paragraphs.

*** List items can contain other blocks, including both nested lists and
delimited blocks.

*** Some delimited blocks can contain other delimited blocks; for example,
examples can contain source code as well as discussion in paragraphs.

** Blocks of text consist of inline text, which themselves can contain markup.


Inline markup includes:

*** Text formatting: bold, italic, superscript, subscript, monospace.

*** Custom markup macros.

*** URLs, including display text.

*** Inline anchors .

*** Cross-references to anchors (IDs of blocks or spans of text), including
display text.

*** Images, audio, and visual files.

*** Index terms.

*** Equations (native support for
http://docs.mathjax.org/en/latest/asciimath.html[AsciiMathML] and
http://docs.mathjax.org/en/latest/tex.html[TeX/LaTeX], via the
https://www.mathjax.org[MathJax] tool).

*** Footnotes.


The Asciidoctor document structure aligns with the RFC XML v2 and v3 structure.
In the following, v3 equivalences are given:

* Header: `<rfc>` attributes, most `front` elements

* Preamble: `front/abstract` and `front/note`

* Sections: `middle/section` elements

* Sections with `bibliography` style attributes: `back/references` elements.

* Sections with `appendix` style attributes: `back/section` elements.

* Paragraphs: `t` elements

* Lists: `ul`, `ol`, `dl` elements

* Delimited blocks: `artwork`, `aside`, `blockquote`, `figure`, `note`,
`sourcecode`, `table`

* Inline markup: `bcp14`, `br`, `cref`, `em`, `eref`, `iref`, `relref`,
`strong`, `sub`, `sup`, `tt`, `xref`

Full details of the  mapping of Asciidoctor elements to RFC XML v2 and v3
elements, and of how to convert Asciidoctor documents to RFC XML, are given in
https://github.com/riboseinc/asciidoctor-rfc/blob/master/README.adoc. The
following gives an overview of how to create an RFC XML document in
Asciidoctor, with some pitfalls to be aware of. Illustrations are in RFC XML
v3, although the converter deals with both versions of RFC XML.

=== Simple illustration

The following is an illustration of a simple AsciiRFC document, and its 
corresponding rendering in RFC XML v3:

[source,asciidoc]
----
=  A Standard for the Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>
:doctype: internet-draft 
:abbrev: IP Datagrams on Avian Carriers
:obsoletes: 10, 120
:updates: 2010, 2120
:status: informational
:name: internet-draft-avian-transmission-00
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:keyword: avians, datagrams
:revdate: 1990-04-01T00:00:00Z
:organization: BBN STC
:phone: (617) 873-4323
:uri: http://bbn.com
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238

[abstract]
Avian carriers can provide high delay, low throughput, and low
altitude service.  The connection topology is limited to a single
point-to-point path for each carrier, used with standard carriers,
but many carriers can be used without significant interference with
each other, outside of early spring. <<frame>> This is because of the 3D ether
space available to the carriers, in contrast to the 1D ether used by
IEEE802.3.  

NOTE: Yes, this is an April Fool's RFC.

[[frame]]
== Frame Format

The IP _datagram_ is *printed*, on a small scroll of paper, in
hexadecimal, with each octet separated by whitestuff and blackstuff.
The scroll of paper is wrapped around one leg of the avian carrier.
A band of duct tape is used to secure the datagram's edges.  The
bandwidth is limited to the leg length.  The MTU is variable, and
paradoxically, generally increases with increased carrier age.  A
typical MTU is 256 milligrams.  Some datagram padding may be needed.<<RFC7253>>

[bibliography]
== Normative References
++++
<reference anchor='RFC7253' target='https://tools.ietf.org/html/rfc7253'>
  <front>
    <title>Guidelines for Writing an IANA Considerations Section in RFCs</title>
    <author initials="T." surname="Krovetz">
      <organization>Sacramento State</organization>
    </author>
    <author initials="P." surname="Rogaway">
      <organization>UC Davis</organization>
    </author>
    <date month='May' year='2014'/>
  </front>
  <seriesInfo name="RFC" value="7253"/>
</reference>
++++
----

The first block of text, from `= A Standard for the Transmission` through to `:code: MA 02238`,
is the document header. It contains a title in the first line, an author attribution, and then
a set of document attributes, conveying information about the document as well as information
about its authors, and ends up either as attributes of the root `rfc` tag, elements of the `front`
tag, or processing instructions.

The following blocks of text, up until the first section header (`==Frame Format`), are the 
document preamble. They are treated by the document converter as containing the document
abstract (`abstract`), followed by any notes (`note`, identified above by the `NOTE:` heading).

The first section header (`==Frame Format`) is preceded by an anchor for that section
(`[[frame]]`). There is a cross-reference to that anchor already in place in the abstract
(`<<frame>>`). The document converter treats the first section of the document as the start of
the `middle` section of the document.

The first section header is followed by a paragraph, which contains some inline formatting
(italics: `_datagram_`; boldface: `*printed*`). The paragraph also contains a citation of
a reference, which in this version of AsciiRef is treated identically to a cross-reference
(`<<RFC7253>>`). (If the bibliography preprocessor were used, it would be encoded differently.)

The following section is tagged with the style attribute `[bibliography]`, which identifies
it as a references container; the document converter accordingly inserts this into the `back`
element of the document. The contents of the references section are in this instance raw XML,
delimited as a passthrough block (with `++++`), which the converter does not alter.

The RFC XML v3 document generated from this AsciiRFC document is:

[source,xml]
----
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<?rfc strict="yes"?>
<?rfc compact="yes"?>
<?rfc subcompact="no"?>
<?rfc toc="yes"?>
<?rfc tocdepth="4"?>
<?rfc symrefs="yes"?>
<?rfc sortrefs="yes"?>
<rfc ipr="trust200902" obsoletes="10, 120" updates="2010, 2120" 
  submissionType="IETF" prepTime="2017-11-21T08:05:30Z" version="3">
<front>
  <title abbrev="IP Datagrams on Avian Carriers">A Standard for the 
    Transmission of IP Datagrams on Avian Carriers</title>
  <seriesInfo name="Internet-Draft" status="informational" 
    stream="IETF" value="internet-draft-avian-transmission-00"/>
  <author fullname="David Waitzman" surname="Waitzman">
    <organization>BBN STC</organization>
    <address>
      <postal>
        <street>10 Moulton Street</street>
        <city>Cambridge</city>
        <code>MA 02238</code>
      </postal>
      <phone>(617) 873-4323</phone>
      <email>dwaitzman@BBN.COM</email>
      <uri>http://bbn.com</uri>
    </address>
  </author>
  <date day="1" month="April" year="1990"/>
  <area>Internet</area>
  <workgroup>Network Working Group</workgroup>
  <keyword>avians</keyword>
  <keyword>datagrams</keyword>

<abstract>
  <t>Avian carriers can provide high delay, low throughput, and low
altitude service.  The connection topology is limited to a single
point-to-point path for each carrier, used with standard carriers,
but many carriers can be used without significant interference with
each other, outside of early spring. <xref target="frame"/> 
This is because of the 3D ether
space available to the carriers, in contrast to the 1D ether used by
IEEE802.3.</t>
</abstract><note>
  <t>Yes, this is an April Fool&#8217;s RFC.</t>
</note>
</front><middle>
<section anchor="frame" numbered="false">
  <name>Frame Format</name>
  <t>The IP <em>datagram</em> is <strong>printed</strong>, on a 
small scroll of paper, in
hexadecimal, with each octet separated by whitestuff and blackstuff.
The scroll of paper is wrapped around one leg of the avian carrier.
A band of duct tape is used to secure the datagram&#8217;s edges.  The
bandwidth is limited to the leg length.  The MTU is variable, and
paradoxically, generally increases with increased carrier age.  A
typical MTU is 256 milligrams.  Some datagram padding may be 
needed.<xref target="RFC7253"/></t>
</section>
</middle><back>
<references anchor="_normative_references">
  <name>Normative References</name>
  <reference anchor="RFC7253" target="https://tools.ietf.org/html/rfc7253">
  <front>
    <title>Guidelines for Writing an IANA Considerations Section in RFCs</title>
    <author initials="T." surname="Krovetz">
      <organization>Sacramento State</organization>
    </author>
    <author initials="P." surname="Rogaway">
      <organization>UC Davis</organization>
    </author>
    <date month="May" year="2014"/>
  </front>
  <seriesInfo name="RFC" value="7253"/>
</reference>
</references>
</back>
</rfc>
----

Some default processing instructions have already been prefixed to the XML. 

Although we do not describe it extensively in this document, our AsciiRFC
converter also generates RFC XML v2 from the same source AsciiRFC. For illustration, 
the foregoing AsciiRFC document generates the following RFC XML v2 output:

[source,xml]
----
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<?rfc strict="yes"?>
<?rfc compact="yes"?>
<?rfc subcompact="no"?>
<?rfc toc="yes"?>
<?rfc tocdepth="4"?>
<?rfc symrefs="yes"?>
<?rfc sortrefs="yes"?>
<rfc ipr="trust200902" obsoletes="10, 120" updates="2010, 2120" 
  category="info" submissionType="IETF" docName="internet-draft-avian-transmission-00">
<front>
  <title abbrev="IP Datagrams on Avian Carriers">A Standard for the 
  Transmission of IP Datagrams on Avian Carriers</title>
  <author fullname="David Waitzman" surname="Waitzman">
    <organization>BBN STC</organization>
    <address>
      <postal>
        <street>10 Moulton Street</street>
        <city>Cambridge</city>
        <code>MA 02238</code>
      </postal>
      <phone>(617) 873-4323</phone>
      <email>dwaitzman@BBN.COM</email>
      <uri>http://bbn.com</uri>
    </address>
  </author>
  <date day="1" month="April" year="1990"/>
  <area>Internet</area>
  <workgroup>Network Working Group</workgroup>
  <keyword>avians</keyword>
  <keyword>datagrams</keyword>

<abstract>
  <t>Avian carriers can provide high delay, low throughput, and low
altitude service.  The connection topology is limited to a single
point-to-point path for each carrier, used with standard carriers,
but many carriers can be used without significant interference with
each other, outside of early spring. <xref target="frame"/> 
This is because of the 3D ether
space available to the carriers, in contrast to the 1D ether used by
IEEE802.3.</t>
</abstract><note title="NOTE">
  <t>Yes, this is an April Fool&#8217;s RFC.</t>
</note>
</front><middle>
<section anchor="frame" title="Frame Format">
  <t>The IP <spanx style="emph">datagram</spanx> is 
<spanx style="strong">printed</spanx>, on a small scroll of paper, in
hexadecimal, with each octet separated by whitestuff and blackstuff.
The scroll of paper is wrapped around one leg of the avian carrier.
A band of duct tape is used to secure the datagram&#8217;s edges.  The
bandwidth is limited to the leg length.  The MTU is variable, and
paradoxically, generally increases with increased carrier age.  A
typical MTU is 256 milligrams.  Some datagram padding may be 
needed.<xref target="RFC7253"/></t>
</section>
</middle><back>
<references title="Normative References">
  <reference anchor="RFC7253" target="https://tools.ietf.org/html/rfc7253">
  <front>
    <title>Guidelines for Writing an IANA Considerations Section in RFCs</title>
    <author initials="T." surname="Krovetz">
      <organization>Sacramento State</organization>
    </author>
    <author initials="P." surname="Rogaway">
      <organization>UC Davis</organization>
    </author>
    <date month="May" year="2014"/>
  </front>
  <seriesInfo name="RFC" value="7253"/>
</reference>
</references>
</back>
</rfc>
----
