
== Document Structure And Asciidoctor Syntax

Asciidoctor syntax is presented in the Asciidoctor user manual
<<Asciidoctor-Manual>>.  AsciiRFC is a subset of Asciidoctor syntax,
with the addition of bibliographic macros
(<<asciidoctor_bibliography>>).

Asciidoctor syntax consists of:

* A document header, containing a title, a list of authors, and
document attributes in lines prefixed with `:`.

* An optional document preamble, separated from document header by a
blank line.

* A number of sections, set off by a section title (a line prefixed
with two or more `=`.)

A section may contain:

* Other sections, whose level of nesting is indicated by the number of
`=` in their header.

* Blocks of text. Blocks can have metadata (including a title, an
anchor for cross-references, and attributes.) 

Blocks can be:

* Paragraphs, which are terminated by blank lines.

* Lists. List items are by default paragraphs, but can span over
multiple paragraphs.

* Delimited blocks (with a line delimiter on either side of them);
these include tables, notes, sidebars, source code, block quotes,
examples, and unprocessed content (e.g. raw XML). Delimited blocks
contain by default one or more paragraphs.

* List items can contain other blocks, including both nested lists and
delimited blocks.

* Some delimited blocks can contain other delimited blocks; for
example, examples can contain source code as well as discussion in
paragraphs.

* Blocks of text consist of inline text, which themselves can contain
markup.


Inline markup includes:

* Text formatting: bold, italic, superscript, subscript, monospace.

* Custom markup macros. (AsciiRFC uses two: `bcp14, comment`.)

* URLs, including display text.

* Inline anchors.

* Cross-references to anchors (IDs of blocks or spans of text),
including display text.

* Images, audio, and visual files. (AsciiRFC only supports images.)

* Index terms.

* Equations (native support for <<AsciiMathML>> and <<TeX-LaTeX>>, via
the <<MathJax>> tool). (Not supported in AsciiRFC, since there is no
RFC XML equivalent.)

* Footnotes. (Not supported in AsciiRFC.)


=== AsciiRFC Mapping To Asciidoctor syntax

The Asciidoctor syntax document structure aligns with the RFC XML v2
and v3 structure.  In the following, RFC XML v3 equivalences are given
to the basic Asciidoctor structure.

Header::
  `<rfc>` attributes, most `front` elements.

Preamble::
  `front/abstract` and `front/note`.

Sections::
  `middle/section` elements.

Sections with `bibliography` style attributes::
  `back/references` elements.

Sections with `appendix` style attributes::
  `back/section` elements.

Paragraphs::
  `t` elements.

Lists::
  `ul`, `ol`, `dl` elements.

Delimited blocks::
  `artwork`, `aside`, `blockquote`, `figure`, `note`, `sourcecode`, `table`.

Inline markup::
  `bcp14`, `br`, `cref`, `em`, `eref`, `iref`, `relref`, `strong`, `sub`,
  `sup`, `tt`, `xref`.

Full details of the mapping of AsciiRFC elements to RFC XML v2 and v3
elements, and of how to convert AsciiRFC documents to RFC XML, are
given in the documentation of <<asciidoctor-rfc>>.


=== Simple Illustration

This section gives an overview of how to create an RFC XML document in
AsciiRFC, with some pitfalls to be aware of.

Illustrations are in RFC XML v3 and RFC XML v2.

A sample AsciiRFC document is provided in <<source-sample-asciirfc>>,
and its corresponding rendering in:

* RFC XML v3 (<<source-sample-asciirfc-output-v3>>)

* RFC XML v2 (<<source-sample-asciirfc-output-v2>>)

[[source-sample-asciirfc]]
.Sample Internet-Draft in AsciiRFC
====
[source,asciidoc]
--------
<CODE BEGINS>
include::../examples/rfc-divination-cfapi/draft-divination-cfapi.adoc[]
<CODE ENDS>
--------
====

The first block of text, from 
`= An API For Calendar-Based Fortune Heuristics Services` through to
`:country_2: USA`, is
the document header. It contains a title in the first line, an author
attribution (`Gabriel Destiny; Charise Luck`), and then a set of 
document attributes, conveying
information about the document as well as information about its
authors. This information ends up either as attributes of the root
`rfc` tag, elements of the `front` tag, or processing instructions.

The following blocks of text, up until the first section header 
(`== Introduction`), are the document preamble. They are
treated by the document converter as containing the document abstract
(`abstract`), followed by any notes if present.

[subs="quotes"]
Section headers delimit the sections of the main body of the document,
starting with `== Introduction`. The document converter treats the first section
of the document as the start of the `middle` section of the document.
The first section header is followed by a paragraph, and other
sections and paragraphs. The number of `=` signs can be one higher than that of
the preceding section header, which indicates that they are subsections
of that section; so `=== Well-Known URI Redirection`
is a subsection of the preceding `== Fortune Heuristics Service Well-Known URI`.

The paragraphs contain some inline formatting
(e.g. boldface: `\*MUST*`, monospace: `{backtick}type{backtick}`), and sections can
also contain blocks other than normal paragraphs; the section
`== Conventions Used in This Document`, for example, contains
a definition list (whose terms are delimited by `::`), and the 
subsection `=== Root of Fortune Path URI ("/")` contains a code snippet
(delimited by `----`, and tagged with the style attribute `[source,json]`,
indicating that this is a JSON sourcecode listing). The document
can also include comments (`//` for inline, `////` for blocks),
which are not rendered when the document is processed.

[subs="quotes"]
The introductory section
contains a citation of a reference, which in this
version of AsciiRFC is treated identically to a cross-reference
(`<<RFC7230>>`) -- the crossreference being to the references
section of the document. Sections and blocks of texts within the
document can also be the target of crossreferences; for example,
the section header `== Fortune Heuristics Service Discovery`
is preceded by the anchor `[#service-discovery]`, and that anchor
is already referenced in the section `== Conventions Used in This Document`.

The third last and second last section are tagged with the style attribute
`[bibliography]`, which identifies them as references containers; the
document converter accordingly inserts them into the `back` element of
the document. The contents of the references sections are in this
instance raw XML, delimited as a passthrough block (with
`{fourpluses}`), which the converter does not alter. 

The final
section is tagged with the style attribute `[appendix]`, and is
treated as such.

The RFC XML v3 document generated from this AsciiRFC document is:

[[source-sample-asciirfc-output-v3]]
.Sample Internet-Draft In AsciiRFC, Output In RFC XML v3 Format
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-divination-cfapi/xml3/draft-divination-cfapi.xml[]
<CODE ENDS>
----
====

Some default processing instructions have already been prefixed to the
XML.

Our AsciiRFC converter can also generate RFC XML v2 from the same
source AsciiRFC, as shown in <<source-sample-asciirfc-output-v2>>.
Output in RFC XML v2 is not extensively described in this document.

[[source-sample-asciirfc-output-v2]]
.Sample Internet-Draft In AsciiRFC, Output In RFC XML v2 Format
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-divination-cfapi/xml2/draft-divination-cfapi.xml[]
<CODE ENDS>
----
====

