[#header]
== Header And Document Attributes

The header gives the document title, followed by an optional author
attribution, and a series of document attributes, with no carriage
return breaks.

=== Title And Basic Attributes

Document attributes are used to populate attributes of the root `rfc`
element, `front` elements, and document-level processing instructions.

* `:doctype:` determines  whether the document will be considered
`rfc` or `internet-draft`, and interprets other attributes
accordingly.

* Certain attributes (`workgroup`, `area`, `keyword`) are comma
delimited, and result in repeated RFC XML elements.

<<source-asciirfc-header>> demonstrates how to set the document header
in AsciiRFC, with its rendering in v3 shown in
<<source-asciirfc-header-v3>>.

[[source-asciirfc-header]]
.AsciiRFC Document Header
====
[source,asciidoc]
----
= Four Yorkshiremen Sketch
Tim Brooke-Taylor <tbt@example.com>
:doctype: internet-draft
:abbrev: 4 Yorkshiremen
:obsoletes: 10, 120
:updates: 2010, 2120
:status: informational
:name: draft-four-yorkshiremen-00
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:keyword: yorkshire, memory
:revdate: 1990-04-01T00:00:00Z
----
====

[[source-asciirfc-header-v3]]
.AsciiRFC Document Header Rendered As RFC XML v3
====
[source,xml]
----
<rfc ipr="trust200902" obsoletes="10, 120" updates="2010, 2120"
    submissionType="IETF" prepTime="2017-11-25T10:13:46Z" version="3">
  <front>
    <title abbrev="4 Yorkshiremen">Four Yorkshiremen Sketch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-four-yorkshiremen-00" />
    <author fullname="Tim Brooke-Taylor" surname="Brooke-Taylor">
      <address>
        <email>tbt@example.com</email>
      </address>
    </author>
    <date day="1" month="April" year="1990" />
    <area>Internet</area>
    <workgroup>Network Working Group</workgroup>
    <keyword>yorkshire</keyword>
    <keyword>memory</keyword>
----
====

=== Detailed Author Information

The document header can spell out further information about authors,
including contact details. The AsciiRFC header is shown in
<<source-asciirfc-header-authors>> with its rendering in RFC XML v3
shown in <<source-asciirfc-header-authors-v3>>.

[[source-asciirfc-header-authors]]
.AsciiRFC Document Header With One Author
====
[source,asciidoc]
----
= Four Yorkshiremen Sketch
Tim Brooke-Taylor <tbt@example.com>
:doctype: internet-draft
:abbrev: 4 Yorkshiremen
:obsoletes: 10, 120
:updates: 2010, 2120
:status: informational
:name: draft-four-yorkshiremen-00
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:keyword: yorkshire, memory
:revdate: 1990-04-01T00:00:00Z
:organization: BBC
:phone: (555) 555-5555
:uri: http://bbn.com
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238
----
====

[[source-asciirfc-header-authors-v3]]
.AsciiRFC Document Header With One Author (RFC XML v3)
====
[source,xml]
----
<rfc ipr="trust200902" obsoletes="10, 120" updates="2010, 2120"
    submissionType="IETF" prepTime="2017-11-25T10:15:02Z" version="3">
  <front>
    <title abbrev="4 Yorkshiremen">Four Yorkshiremen Sketch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-four-yorkshiremen-00" />
    <author fullname="Tim Brooke-Taylor" surname="Brooke-Taylor">
      <organization>BBC</organization>
      <address>
        <postal>
          <street>10 Moulton Street</street>
          <city>Cambridge</city>
          <code>MA 02238</code>
        </postal>
        <phone>(555) 555-5555</phone>
        <email>tbt@example.com</email>
        <uri>http://bbn.com</uri>
      </address>
    </author>
    <date day="1" month="April" year="1990" />
    <area>Internet</area>
    <workgroup>Network Working Group</workgroup>
    <keyword>yorkshire</keyword>
    <keyword>memory</keyword>
----
====

Details of a second, third etc. author, including their organization and
contact details, are provided by suffixing the relevant author attributes with
`_2`, `_3`  etc., as shown in <<source-asciirfc-header-mauthors>> and
its v3 rendering <<source-asciirfc-header-mauthors-v3>>.

[[source-asciirfc-header-mauthors]]
.AsciiRFC Document Header With Multiple Authors
====
[source,asciidoc]
----
= Four Yorkshiremen Sketch
Tim Brooke-Taylor <tbt@example.com>; John Cleese <jc@example.com>
:doctype: internet-draft
:status: informational
:name: draft-four-yorkshiremen-00
:ipr: trust200902
:organization: BBC
:phone: (555) 555-5555
:uri: http://example.com
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238
:forename_initials: T.
:lastname: Brooke-Taylor
:street: 12 Moulton Street
:city: London
:country: United Kingdom
:forename_initials_2: J.
:lastname_2: Cleese
:uri_2: https://twitter.com/johncleese
----
====

[[source-asciirfc-header-mauthors-v3]]
.AsciiRFC Document Header With Multiple Authors (RFC XML v3)
====
[source,xml]
----
<rfc ipr="trust200902" submissionType="IETF"
    prepTime="2017-11-25T10:19:32Z" version="3">
  <front>
    <title>Four Yorkshiremen Sketch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-four-yorkshiremen-00" />
    <author fullname="Tim Brooke-Taylor"
        surname="Brooke-Taylor" initials="T.">
      <organization>BBC</organization>
      <address>
        <postal>
          <street>12 Moulton Street</street>
          <city>London</city>
          <code>MA 02238</code>
          <country>United Kingdom</country>
        </postal>
        <phone>(555) 555-5555</phone>
        <email>tbt@example.com</email>
        <uri>http://example.com</uri>
      </address>
    </author>
    <author fullname="John Cleese" surname="Cleese" initials="J.">
      <address>
        <email>jc@example.com</email>
        <uri>https://twitter.com/johncleese</uri>
      </address>
    </author>
    <date day="25" month="November" year="2017" />
----
====

The initial author attribution in AsciiRFC, e.g.
`Tim Brooke-Taylor <\tbt@bbc.co.uk>; John Cleese <\jc@bbc.co.uk>`
in the example above, expects a strict format of First Name, zero or
more Middle Names, Last name, and cannot process honorifics like "Dr."
or suffixes like "Jr.".

Name attributes with any degree of complexity should be overriden by
using the `:fullname:` and `:lastname:` attributes. The AsciiRFC
`:forename_initials:` attribute replaces the built-in Asciidoctor
`:initials:` attribute (which includes the surname initial), and is
not automatically populated from the name attribution.


=== XML Processing Information

A document header may also contain attribute headers which are treated
as XML processing instructions. An AsciiRFC example is shown in
<<source-asciirfc-header-pi>> with its rendering in
<<source-asciirfc-header-pi-v3>>.

[[source-asciirfc-header-pi]]
.AsciiRFC Document Header With XML Processing Information
====
[source,asciidoc]
----
= Four Yorkshiremen Sketch
Tim Brooke-Taylor <tbt@example.com>
:doctype: internet-draft
:status: informational
:name: draft-four-yorkshiremen-00
:ipr: trust200902
:revdate: 1990-04-01T00:00:00Z
:rfcedstyle: yes
:text-list-symbols: yes
:rfc2629xslt: true
----
====

[[source-asciirfc-header-pi-v3]]
.AsciiRFC Document Header With XML Processing Information (RFC XML v3)
====
[source,xml]
----
<rfc ipr="trust200902" submissionType="IETF"
    prepTime="2017-11-25T10:21:56Z" version="3">
  <front>
    <title>Four Yorkshiremen Sketch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-four-yorkshiremen-00" />
    <author fullname="Tim Brooke-Taylor" surname="Brooke-Taylor">
      <address>
        <email>tbt@example.com</email>
      </address>
    </author>
    <date day="1" month="April" year="1990" />
----
====


=== AsciiRFC-specific Document Attributes

A few document attributes are specific to the operation of the RFC XML
document converter:

`:no-rfc-bold-bcp14: false` :: 
  overrides the wrapping by default of boldface uppercase BCP14
  <<RFC2119>> words (e.g. `\*MUST NOT*`) with the `bcp14` element.

`:smart-quotes: false` ::
  overrides Asciidoctor's conversion of straight quotes and
  apostrophes to smart quotes and apostrophes.

`:inline-definition-lists: true` ::
  overrides the RFC XML v2 `idnits` requirement that a blank line be
  inserted between a definition list term and its definition.

[[source-asciirfc-header-rfc]]
.AsciiRFC Document Header Without RFC-specific Attributes
====
[source,asciidoc]
----
= Four Yorkshiremen Sketch
Tim Brooke-Taylor <tbt@example.com>
:doctype: internet-draft
:status: informational
:name: draft-four-yorkshiremen-00

== Section 1
The specification *MUST NOT* use the word _doesn't_.
----
====

[[source-asciirfc-header-rfc-v3]]
.AsciiRFC Document Header Without RFC-specific Attributes (RFC XML v3)
====
[source,xml]
----
<rfc submissionType="IETF" prepTime="2017-11-25T10:23:39Z" version="3">
  <front>
    <title>Four Yorkshiremen Sketch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-four-yorkshiremen-00" />
    <author fullname="Tim Brooke-Taylor" surname="Brooke-Taylor">
      <address>
        <email>tbt@example.com</email>
      </address>
    </author>
    <date day="25" month="November" year="2017" />
  </front>
  <middle>
    <section anchor="_section_1" numbered="false">
      <name>Section 1</name>
      <t>The specification  <bcp14>MUST NOT</bcp14>
        use the word <em> doesn&#8217;t</em>.</t>
    </section>
  </middle>
</rfc>
----
====

[[source-asciirfc-header-override]]
.AsciiRFC Document Header With Overridden RFC-specific Attributes
====
[source,asciidoc]
----
= Four Yorkshiremen Sketch
Tim Brooke-Taylor <tbt@example.com>
:doctype: internet-draft
:status: informational
:name: draft-four-yorkshiremen-00
:no-rfc-bold-bcp14: false
:smart-quotes: false

== Section 1
The specification *MUST NOT* use the word _doesn't_.
----
====

[[source-asciirfc-header-override-v3]]
.AsciiRFC Document Header With Overridden RFC-specific Attributes (RFC XML v3)
====
[source,xml]
----
<rfc submissionType="IETF" prepTime="2017-11-25T10:23:39Z" version="3">
  <front>
    <title>Four Yorkshiremen Sketch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-four-yorkshiremen-00" />
    <author fullname="Tim Brooke-Taylor" surname="Brooke-Taylor">
      <address>
        <email>tbt@example.com</email>
      </address>
    </author>
    <date day="25" month="November" year="2017" />
  </front>
  <middle>
    <section anchor="_section_1" numbered="false">
      <name>Section 1</name>
      <t>The specification <strong>MUST NOT</strong>
        use the word <em>doesn't</em>.</t>
    </section>
  </middle>
</rfc>
----
====

