== Header And Document Attributes

The header gives the document title, followed by an optional author
attribution, and a series of document attributes, with no carriage return
breaks.

For example:

[source,asciidoc]
----
= Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>
:doctype: internet-draft 
:abbrev: IP Datagrams on Avian Carriers
:obsoletes: 10, 120
:updates: 2010, 2120
:status: informational
:name: internet-draft-avian-transmission-00
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:keyword: avians, datagrams
:revdate: 1990-04-01T00:00:00Z
----

The document attributes are used to populate attributes of the root `rfc` 
element, `front` elements, and document-level processing instructions. 

* `:doctype:` determines  whether the document will be considered `rfc` or
`internet-draft`, and interprets other attributes accordingly. 

* Certain attributes (`workgroup`, `area`, `keyword`) are comma delimited, and result in repeated RFC XML elements.

The foregoing Asciidoc renders into RFC XML v3 as:

[source,xml]
----
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<rfc ipr="trust200902" obsoletes="10, 120" updates="2010, 2120" 
  submissiontype="IETF" preptime="2017-11-18T01:52:35Z" version="3">
    <front>
        <title abbrev="IP Datagrams on Avian Carriers">
            A Standard for the Transmission of IP 
            Datagrams on Avian Carriers
        </title>
        <seriesinfo name="Internet-Draft" status="informational" 
          stream="IETF" value="internet-draft-avian-transmission-00" />
        <author fullname="David Waitzman" surname="Waitzman">
            <address>
                <email>dwaitzman@BBN.COM</email>
            </address>
        </author>
        <date day="1" month="April" year="1990" />
        <area>Internet</area>
        <workgroup>Network Working Group</workgroup>
        <keyword>avians</keyword>
        <keyword>datagrams</keyword>
----

The document header can spell out further information about authors, including
contact details:

[source,asciidoc]
----
= Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>
:doctype: internet-draft 
:abbrev: IP Datagrams on Avian Carriers
:obsoletes: 10, 120
:updates: 2010, 2120
:status: informational
:name: internet-draft-avian-transmission-00
:ipr: trust200902
:revdate: 1990-04-01T00:00:00Z
:organization: BBN STC
:phone: (617) 873-4323
:uri: http://bbn.com
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238
----

[source,xml]
----
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<rfc ipr="trust200902" obsoletes="10, 120" updates="2010, 2120" 
  submissiontype="IETF" preptime="2017-11-18T01:52:35Z" version="3">
    <front>
        <title abbrev="IP Datagrams on Avian Carriers">
            A Standard for the Transmission of IP 
            Datagrams on Avian Carriers
        </title>
        <seriesinfo name="Internet-Draft" status="informational" 
          stream="IETF" value="internet-draft-avian-transmission-00" />
        <author fullname="David Waitzman" surname="Waitzman">
            <organization>BBN STC</organization>
            <address>
                <postal>
                    <street>10 Moulton Street</street>
                    <city>Cambridge</city>
                    <code>MA 02238</code>
                </postal>
                <phone>(617) 873-4323</phone>
                <email>dwaitzman@BBN.COM</email>
                <uri>http://bbn.com</uri>
            </address>
        </author>
        <date day="1" month="April" year="1990" />
----

Details of a second, third etc. author, including their organization and
contact details, are provided by suffixing the relevant author attributes
with `_2`, `_3`  etc.:

[source,asciidoc]
----
= Transmission of IP Datagrams on Avian Carriers
John Doe Horton <jh@email.com>; Billy Thornton <bthornton@email.com>
:fullname: John Doe Horton
:lastname: Horton
:forename_initials: J. D.
:organization: Ribose
:fax: 555 5555
:email: jh@email.com
:uri: http://example.com
:phone: 555 5655
:street: 57 Mt Pleasant St
:city: Dullsville
:region: NSW
:country: Australia
:code: 3333
:fullname_2: Billy Thornton
:lastname_2: Thornton
:forename_initials_2: B. B.
:role_2: editor
:organization_2: IBM
:fax_2: 555 6666
:email_2: bthornton@email.com
:uri_2: http://ibm.com
:phone_2: 555 6655
:street_2: 67 Mt Pleasant St
:city_2: Dulltown
:region_2: VIC
:country_2: UK
:code_2: 44444
----

[source,xml]
----
<rfc submissionType="IETF" prepTime="2017-11-21T09:28:01Z" version="3">
<front>
  <title>Transmission of IP Datagrams on Avian Carriers</title>
  <author fullname="John Doe Horton" surname="Horton" initials="J. D.">
    <organization>Ribose</organization>
    <address>
      <postal>
        <street>57 Mt Pleasant St</street>
        <city>Dullsville</city>
        <region>NSW</region>
        <code>3333</code>
        <country>Australia</country>
      </postal>
      <phone>555 5655</phone>
      <facsimile>555 5555</facsimile>
      <email>jh@email.com</email>
      <uri>http://example.com</uri>
    </address>
  </author>
  <author fullname="Billy Thornton" surname="Thornton" 
    initials="B. B." role="editor">
    <organization>IBM</organization>
    <address>
      <postal>
        <street>67 Mt Pleasant St</street>
        <city>Dulltown</city>
        <region>VIC</region>
        <code>44444</code>
        <country>UK</country>
      </postal>
      <phone>555 6655</phone>
      <facsimile>555 6666</facsimile>
      <email>bthornton@email.com</email>
      <uri>http://ibm.com</uri>
    </address>
  </author>
----

The initial author attribution in Asciidoctor, e.g. 
`John Doe Horton <\john.doe@email.com>; 
Billy Bob Thornton <\billy.thornton@email.com>`
in the example above, expects a strict format of First Name, zero or
more Middle Names, Last name, and cannot process honorifics like "Dr"
or suffixes like "Jr". Name attributes with any degree of complexity
should be overriden by using the `:fullname:` and `:lastname:`
attributes. The `:forename_initials:` attribute replaces the built-in Asciidoctor
`:initials:` attribute (which includes the surname initial), and is not
automatically populated from the name attribution.

A document header may also contain attribute headers which are treated
as XML processing instructions:

[source,asciidoc]
----
= Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>
:doctype: internet-draft 
:status: informational
:name: internet-draft-avian-transmission-00
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:revdate: 1990-04-01T00:00:00Z
:rfcedstyle: yes
:text-list-symbols: yes
:rfc2629xslt: true
----

[source,xml]
----
<?xml version="1.0" encoding="US-ASCII"?>
<?xml-stylesheet type="text/xsl" href="rfc2629.xslt"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<?rfc rfcedstyle="yes"?>
<?rfc text-list-symbols="yes"?>
<rfc ipr="trust200902" submissionType="IETF" 
  prepTime="2017-11-21T09:29:41Z" version="3">
<front>
  <title>Transmission of IP Datagrams on Avian Carriers</title>
  <seriesInfo name="Internet-Draft" status="informational" 
    stream="IETF" value="internet-draft-avian-transmission-00"/>
  <author fullname="David Waitzman" surname="Waitzman">
    <address>
      <email>dwaitzman@BBN.COM</email>
    </address>
  </author>
  <date day="1" month="April" year="1990"/>
  <area>Internet</area>
  <workgroup>Network Working Group</workgroup>
----

A few document attributes are specific to the operation of the RFC XML document converter:

`:no-rfc-bold-bcp14: false` :: overrides the wrapping by default of boldface uppercase
BCP14 <<RFC2119>> words (e.g. `\*MUST NOT*`) with the `bcp14` element.

`:smart-quotes: false` :: overrides Asciidoctor's conversion of straight quotes and apostrophes to smart quotes and apostrophes.

`:inline-definition-lists: true` :: overrides the RFC XML v2 `idnits` requirement that a blank line be inserted between a definition list term and its definition.

[source,asciidoc]
----
= A Standard for the Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>
:doctype: internet-draft
:status: informational
:name: internet-draft-avian-transmission-00

== Section 1
The specification *MUST NOT* use the word _doesn't_.
----

[source,xml]
----
<rfc submissionType="IETF" 
  prepTime="2017-11-21T11:14:35Z" version="3">
<front>
  <title>A Standard for the Transmission of IP Datagrams 
    on Avian Carriers</title>
  <seriesInfo name="Internet-Draft" status="informational" 
    stream="IETF" value="internet-draft-avian-transmission-00"/>
  <author fullname="David Waitzman" surname="Waitzman">
    <address>
      <email>dwaitzman@BBN.COM</email>
    </address>
  </author>
  <date day="21" month="November" year="2017"/>

</front><middle>
<section anchor="_section_1" numbered="false">
  <name>Section 1</name>
  <t>The specification <bcp14>MUST NOT</bcp14> use 
     the word <em>doesn&#8217;t</em>.</t>
</section>
</middle>
</rfc>
----

[source,asciidoc]
----
= A Standard for the Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>
:doctype: internet-draft
:status: informational
:name: internet-draft-avian-transmission-00
:no-rfc-bold-bcp14: false
:smart-quotes: false

== Section 1
The specification *MUST NOT* use the word _doesn't_.
----

[source,xml]
----
<rfc submissionType="IETF" 
  prepTime="2017-11-21T11:14:35Z" version="3">
<front>
  <title>A Standard for the Transmission of IP Datagrams 
    on Avian Carriers</title>
  <seriesInfo name="Internet-Draft" status="informational" 
    stream="IETF" value="internet-draft-avian-transmission-00"/>
  <author fullname="David Waitzman" surname="Waitzman">
    <address>
      <email>dwaitzman@BBN.COM</email>
    </address>
  </author>
  <date day="21" month="November" year="2017"/>

</front><middle>
<section anchor="_section_1" numbered="false">
  <name>Section 1</name>
  <t>The specification <strong>MUST NOT</strong> use 
     the word <em>doesn't</em>.</t>
</section>
</middle>
</rfc>
----
