== Header And Document Attributes

The header gives the document title, followed by an optional author
attribution, and a series of document attributes, with no carriage return
breaks.

For example:

// TODO: use a simpler example
[source,asciidoc]
----
= Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>
:doctype: internet-draft 
:abbrev: IP Datagrams on Avian Carriers
:obsoletes: 10, 120
:updates: 2010, 2120
:status: informational
:name: internet-draft-avian-transmission-00
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:keyword: avians, datagrams
:revdate: 1990-04-01T00:00:00Z
:organization: BBN STC
:phone: (617) 873-4323
:uri: http://bbn.com
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238
:rfcedstyle: yes
:text-list-symbols: yes
:rfc2629xslt: true
----

The document attributes are used to populate `rfc` attributes, `front`
elements, and document-level processing instructions. 

* `:doctype:` determines  whether the document will be considered `rfc` or
`internet-draft`, and interprets other attributes accordingly. 

* Certain attributes (`workgroup`, `area`, `keyword`) are comma delimited, and result in repeated RFC XML elements.

* A few attributes are specific to the operation of the RFC XML document converter: 

** `:no-rfc-bold-bcp14: false` overrides the conversion of boldface uppercase 
BCP14 <<RFC2119>> words with the `bcp14` element.

** `:smart-quotes false:` overrides Asciidoctor's conversion of straight quotes and apostrophes to smart quotes and apostrophes.

** `:inline-definition-lists: true` overrides the RFC XML v2 `idnits` requirement that a blank line be inserted between a definition list term and its definition.

The foregoing Asciidoc renders into RFC XML v3 as:

[source,xml]
----
<?xml version="1.0" encoding="US-ASCII"?>
<?xml-stylesheet type="text/xsl" href="rfc2629.xslt"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<?rfc rfcedstyle="yes"?>
<?rfc text-list-symbols="yes"?>
<?rfc strict="yes"?>
<?rfc compact="yes"?>
<?rfc subcompact="no"?>
<?rfc toc="yes"?>
<?rfc tocdepth="4"?>
<?rfc symrefs="yes"?>
<?rfc sortrefs="yes"?>
<rfc ipr="trust200902" obsoletes="10, 120" updates="2010, 2120" 
  submissiontype="IETF" preptime="2017-11-18T01:52:35Z" version="3">
    <front>
        <title abbrev="IP Datagrams on Avian Carriers">
            A Standard for the Transmission of IP 
            Datagrams on Avian Carriers
        </title>
        <seriesinfo name="Internet-Draft" status="informational" 
          stream="IETF" value="internet-draft-avian-transmission-00" />
        <author fullname="David Waitzman" surname="Waitzman">
            <organization>BBN STC</organization>
            <address>
                <postal>
                    <street>10 Moulton Street</street>
                    <city>Cambridge</city>
                    <code>MA 02238</code>
                </postal>
                <phone>(617) 873-4323</phone>
                <email>dwaitzman@BBN.COM</email>
                <uri>http://bbn.com</uri>
            </address>
        </author>
        <date day="1" month="April" year="1990" />
        <area>Internet</area>
        <workgroup>Network Working Group</workgroup>
        <keyword>avians</keyword>
        <keyword>datagrams</keyword>
----

Details of a second, third etc. author, including their organization and
contact details, are provided by suffixing the author attribute with `_2`, `_3`
etc.:

[source,asciidoc]
----
John Doe Horton <john.doe@email.com>; 
  Billy Bob Thornton <billy.thornton@email.com>
:fullname: John Doe Horton
:lastname: Horton
:forename_initials: J. D.
:role: editor
:organization: Ribose
:fax: 555 5555
:email: john.doe@email.com
:uri: http://example.com
:phone: 555 5655
:street: 57 Mt Pleasant St
:city: Dullsville
:region: NSW
:country: Australia
:code: 3333
:fullname_2: Billy Bob Thornton
:lastname_2: Thornton
:forename_initials_2: B. B.
:role_2: editor
:organization_2: IBM
:fax_2: 555 6666
:email_2: billy.thornton@email.com
:uri_2: http://ibm.com
:phone_2: 555 6655
:street_2: 67 Mt Pleasant St
:city_2: Dulltown
:region_2: VIC
:country_2: UK
:code_2: 44444
----

The initial author attribution in Asciidoctor, e.g. `John Doe Horton
<\john.doe@email.com>; Billy Bob Thornton <\billy.thornton@email.com>`
in the example above, expects a strict format of First Name, zero or
more Middle Names, Last name, and cannot process honorifics like "Dr"
or suffixes like "Jr". Name attributes with any degree of complexity
should be overriden by using the `:fullname:` and `:lastname:`
attributes. The `:forename_initials:` replaces the built-in
`:initials:` attribute (which includes the surname initial), and is not
automatically populated from the name attribution.


