
== Header And Document Attributes

The header gives the document title, followed by an optional author
attribution, and a series of document attributes, with no empty lines.

=== Title And Basic Attributes

Document attributes are used to populate attributes of the root `rfc`
element, `front` elements, and document-level processing instructions.

* `:doctype:` determines  whether the document will be considered
`rfc` or `internet-draft`, and interprets other attributes
accordingly.

* Certain attributes (`workgroup`, `area`, `keyword`) are comma
delimited, and result in repeated RFC XML elements.

<<source-asciirfc-header>> demonstrates how to set the document header
in AsciiRFC, with its rendering in RFC XML v3 shown in
<<source-asciirfc-header-v3>>.

[[source-asciirfc-header]]
.AsciiRFC Document Header
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[lines=1..15]
<CODE ENDS>
----
====

[[source-asciirfc-header-v3]]
.AsciiRFC Document Header Rendered As RFC XML v3
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[lines="13..23,35,37..40"]
<CODE ENDS>
----
====

=== Detailed Author Information

The document header can spell out further information about authors,
including contact details. The AsciiRFC header is shown in
<<source-asciirfc-header-authors>> with its rendering in RFC XML v3
shown in <<source-asciirfc-header-authors-v3>>.

[[source-asciirfc-header-authors]]
.AsciiRFC Document Header With One Author
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[lines=1..25]
<CODE ENDS>
----
====

[[source-asciirfc-header-authors-v3]]
.AsciiRFC Document Header With One Author (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[lines="13..40"]
<CODE ENDS>
----
====

Details of a second, third etc. author, including their organization and
contact details, are provided by suffixing the relevant author attributes with
`_2`, `_3`  etc., as shown in <<source-asciirfc-header-mauthors>> and
its RFC XML v3 rendering <<source-asciirfc-header-mauthors-v3>>.

[[source-asciirfc-header-mauthors]]
====
[source,asciidoc]
--------
<CODE BEGINS>
include::../examples/rfc-divination-cfapi/draft-divination-cfapi.adoc[lines=1..31]
<CODE ENDS>
--------
====

[[source-asciirfc-header-mauthors-v3]]
.AsciiRFC Document Header With Multiple Authors (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-divination-cfapi/xml3/draft-divination-cfapi.xml[lines=11..47]
<CODE ENDS>
----
====

The initial author attribution in AsciiRFC, e.g.
`Gabriel Destiny; Charlise Luck`
in the example above, expects a strict format of First Name, zero or
more Middle Names, Last name, and cannot process honorifics like "Dr."
or suffixes like "Jr.".

Name attributes with any degree of complexity should be overriden by
using the `:fullname:` and `:lastname:` attributes. The AsciiRFC
`:forename_initials:` attribute replaces the built-in Asciidoctor
syntax `:initials:` attribute (which includes the surname initial),
and is not automatically populated from the name attribution.

=== XML Processing Information

A document header may also contain attribute headers which are treated
as XML processing instructions. An AsciiRFC example is shown in
<<source-asciirfc-header-pi>> with its rendering in
<<source-asciirfc-header-pi-v3>>. (Note that several processing
instructions are included by default in the output of the AsciiRFC
processor.)

[[source-asciirfc-header-pi]]
.AsciiRFC Document Header With XML Processing Information
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[lines="1..9,12-15,26..27"]
<CODE ENDS>
----
====

[[source-asciirfc-header-pi-v3]]
.AsciiRFC Document Header With XML Processing Information (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[lines="1..23,35"]
<CODE ENDS>
----
====

In the foregoing, values for the processing instructions `strict`, `compact`,
`toc` etc are included by default; but `comments` and `notedraftinprogress`
are included as specified in the AsciiRFC document header. The default
values provided for processing instructions can in fact be overriden through
the AsciiRFC document header.


=== AsciiRFC-specific Document Attributes

A few document attributes are specific to the operation of the RFC XML
document converter:

`:no-rfc-bold-bcp14: false` :: 
  overrides the wrapping by default of boldface uppercase BCP14
  <<RFC2119>> words (e.g. `\*MUST NOT*`) with the `bcp14` element.

`:smart-quotes: false` ::
  overrides Asciidoctor's conversion of straight quotes and
  apostrophes to smart quotes and apostrophes.

`:inline-definition-lists: true` ::
  overrides the RFC XML v2 `idnits` requirement that a blank line be
  inserted between a definition list term and its definition.

[[source-asciirfc-header-rfc]]
.AsciiRFC Document Header Without RFC-specific Attributes
====
[source,asciidoc]
----
<CODE BEGINS>
= The Holy Hand Grenade of Antioch
Arthur son of Uther Pendragon
:doctype: internet-draft
:status: informational
:name: draft-camelot-holy-grenade-00

== Section 1
The specification *MUST NOT* use the word _doesn't_.
<CODE ENDS>
----
====

[[source-asciirfc-header-rfc-v3]]
.AsciiRFC Document Header Without RFC-specific Attributes (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
<rfc submissionType="IETF" prepTime="2017-11-25T10:23:39Z" version="3">
  <front>
    <title>The Holy Hand Grenade of Antioch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-camelot-holy-grenade-00" />
    <author fullname="Arthur son of Uther Pendragon" surname="Pendragon" 
initials="A.">
    </author>
    <date day="25" month="November" year="2017" />
  </front>
  <middle>
    <section anchor="_section_1" numbered="false">
      <name>Section 1</name>
      <t>The specification  <bcp14>MUST NOT</bcp14>
        use the word <em> doesn&#8217;t</em>.</t>
    </section>
  </middle>
</rfc>
<CODE ENDS>
----
====

[[source-asciirfc-header-override]]
.AsciiRFC Document Header With Overridden RFC-specific Attributes
====
[source,asciidoc]
----
<CODE BEGINS>
= The Holy Hand Grenade of Antioch
Arthur son of Uther Pendragon
:doctype: internet-draft
:status: informational
:name: draft-camelot-holy-grenade-00
:no-rfc-bold-bcp14: false
:smart-quotes: false

== Section 1
The specification *MUST NOT* use the word _doesn't_.
<CODE ENDS>
----
====

[[source-asciirfc-header-override-v3]]
.AsciiRFC Document Header With Overridden RFC-specific Attributes (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
<rfc submissionType="IETF" prepTime="2017-11-25T10:23:39Z" version="3">
  <front>
    <title>The Holy Hand Grenade of Antioch</title>
    <seriesInfo name="Internet-Draft" status="informational"
        stream="IETF" value="draft-camelot-holy-grenade-00" />
    <author fullname="Arthur son of Uther Pendragon" surname="Pendragon" 
initials="A.">
    </author>
    <date day="25" month="November" year="2017" />
  </front>
  <middle>
    <section anchor="_section_1" numbered="false">
      <name>Section 1</name>
      <t>The specification <strong>MUST NOT</strong>
        use the word <em>doesn't</em>.</t>
    </section>
  </middle>
</rfc>
<CODE ENDS>
----
====

