== Sections and Paragraphs

Section headers are given with a sequence of `=`, the number of `=`
giving the header level: a single `=` is used for the opening of the
document, and a minimum of two `=` symbols are used to prefix a
section immediately 

The document itself opens with a single `=`, and sections within it
must be started with a minimum of `==`.  

Section numbering is toggled with the
in-document attribute `:sectnums:` (on), `:sectnums!:` (off). The
`toc` attribute can also be set on sections, indicating whether the
section can be included in the document's table of contents.

<<source-asciirfc-sections>> shows how sections and paragraphs are
used in AsciiRFC, and its rendered form shown in
<<source-asciirfc-sections-v3>>.

[[source-asciirfc-sections]]
.AsciiRFC With Sections
====
[source,asciidoc]
----
:sectnums:
[toc=exclude]
== Section 1
Para 1

=== Subsection 1.1
Para 1a

:sectnums!:
[toc=default]
=== Subsection 1.2
Para 2

==== Subsection 1.2.1
Para 3
----
====

[[source-asciirfc-sections-v3]]
.AsciiRFC With Sections (RFC XML v3)
====
[source,xml]
----
<section anchor="_section_1" toc="exclude" numbered="true">
  <name>Section 1</name>
  <t>Para 1</t>
  <section anchor="_subsection_1_1" numbered="true">
    <name>Subsection 1.1</name>
    <t>Para 1a</t>
  </section>
  <section anchor="_subsection_1_2" toc="default" numbered="false">
    <name>Subsection 1.2</name>
    <t>Para 2</t>
    <section anchor="_subsection_1_2_1" numbered="false">
      <name>Subsection 1.2.1</name>
      <t>Para 3</t>
    </section>
  </section>
</section>
----
====


Note that skipped sections, such as defining a section using `====`
within a section defined using `==`, is not allowed in AsciiRFC
syntax. Doing so will trigger an error with the following message:

----
asciidoctor: WARNING: [filename]: line [X]:
  section title out of sequence: expected level 2, got level 3
----

