== Sections and Paragraphs

Section headers are given with a sequence of `=`, the number of `=`
giving the header level: a single `=` is used for the opening of the
document, and a minimum of two `=` symbols are used to prefix a
section immediately 

The document itself opens with a single `=`, and sections within it
must be started with a minimum of `==`.  

Section numbering is toggled with the
in-document attribute `:sectnums:` (on), `:sectnums!:` (off). The
`toc` attribute can also be set on sections, indicating whether the
section can be included in the document's table of contents.

<<source-asciirfc-sections>> shows how sections and paragraphs are
used in AsciiRFC, and its rendered form shown in
<<source-asciirfc-sections-v3>>.

[[source-asciirfc-sections]]
.AsciiRFC With Sections
====
[source,asciidoc]
----
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=sectnums]
----
====

[[source-asciirfc-sections-v3]]
.AsciiRFC With Sections (RFC XML v3)
====
[source,xml]
----
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tags=sectnums]
----
====


Note that skipped sections, such as defining a section using `====`
within a section defined using `==`, is not allowed in AsciiRFC
syntax. Doing so will trigger an error with the following message:

[source,console]
----
asciidoctor: WARNING: _filename_: line _X_:
  section title out of sequence: expected level 2, got level 3
----

