[#lists]
== Lists

=== Basic Lists

AsciiRFC supports ordered, unordered, and definition lists.
Indentation of ordered and unordered lists is indicated by repeating
the list item prefix (`*` and `.` respectively); for definition
lists, by incrementing the number of definition term delimiters
(`::`).

List attributes can be used to specify the type of symbol used for
ordered lists.

An example of an unordered list is shown in
<<source-asciirfc-unordered-list>> (with its rendered version in
<<source-asciirfc-unordered-list-v3>>). An example of an ordered list 
with ordered and unordered sublists is
shown in <<source-asciirfc-ordered-list>> (with its rendered version
in <<source-asciirfc-ordered-list-v3>>). An example of a definition
list is shown in <<source-asciirfc-definition-list>> (with its
rendered version in <<source-asciirfc-definition-list-v3>>).

[[source-asciirfc-unordered-list]]
.AsciiRFC With Unordered lists
====
[source,asciidoc]
----
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=ul]
----
====

[[source-asciirfc-unordered-list-v3]]
.AsciiRFC With Unordered Lists (RFC XML v3)
====
[source,asciidoc]
----
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=ul1]
----
====

[[source-asciirfc-ordered-list]]
.AsciiRFC With Ordered lists
====
[source,asciidoc]
----
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=ol]
----
====

[[source-asciirfc-ordered-list-v3]]
.AsciiRFC With Ordered Lists (RFC XML v3)
====
[source,xml]
----
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=ol1]
----
====

[[source-asciirfc-definition-list]]
.AsciiRFC With Definition lists
====
[source,asciidoc]
----
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=dl]
----
====

[[source-asciirfc-definition-list-v3]]
.AsciiRFC With Definition Lists (RFC XML v3)
====
[source,xml]
----
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=dl1]
----
====


=== List Continuation

A list item by default spans a single paragraph. A following paragraph
or other block element can be appended to the current list item by
prefixing it with `+` in a separate line.

See the "List Continuation" section in <<Asciidoctor-Manual>> for more
information.

An example of list continuation with text is shown in
<<source-asciirfc-list-text>> with its rendered version in
<<source-asciirfc-list-text-v3>>.

[[source-asciirfc-list-text]]
.AsciiRFC List With Text Continuation
====
[source,asciidoc]
----
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=listcontinuation]
----
====

[[source-asciirfc-list-text-v3]]
.AsciiRFC List With Text Continuation (RFC XML v3)
====
[source,xml]
----
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=listcontinuation1]
----
====

(Multiple paragraphs are not permitted within a list item in RFC XML
v2.  The RFC XML converter deals with this by converting paragraph
breaks into line breaks within a list item.)

List continuations can also be embed to populate a list item with a
sequence of blocks as a unit (in an Asciidoctor syntax open block).

An example of list continuation with block is shown in
<<source-asciirfc-list-block>> with its rendered version in
<<source-asciirfc-list-block-v3>>.

[[source-asciirfc-list-block]]
.AsciiRFC List With Block Continuation
====
[source,asciidoc]
-----
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=listcontinuationblock]
-----
====

[[source-asciirfc-list-block-v3]]
.AsciiRFC List With Block Continuation (RFC XML v3)
====
[source,xml]
----
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=listcontinuationblock1]
----
====

AsciiDoc, and thus AsciiRFC, considers paragraphs to be the basic
level of blocks, and does not permit lists to be nested within them:
text after a list is considered to be a new paragraph.

Therefore, markup as shown in <<source-asciirfc-list-impossible>>
cannot be generated via AsciiRFC.

[[source-asciirfc-list-impossible]]
.This RFC XML v3 Output Cannot Be Generated Using AsciiRFC
====
[source,xml]
----
<t>
  This is the start of a paragraph.
  <ul>
    <li>List Entry 1</li>
    <li>
      <t>List Entry 2</t>
      <t>Note 2.</t>
    </li>
  </ul>
  And this is the continuation of the paragraph.
</t>
----
====

