[#lists]
== Lists

=== Basic Lists

AsciiRFC supports ordered, unordered, and definition lists.
Indentation of ordered and unordered lists is indicated by repeating
the list item prefix (`*` and `.` respectively).

List attributes can be used to specify the type of symbol used for
ordered lists.

An example of an unordered list is shown in
<<source-asciirfc-unordered-list>> (with its rendered version in
<<source-asciirfc-unordered-list-v3>>), and that of an ordered list is
shown in <<source-asciirfc-ordered-list>> (with its rendered version
in <<source-asciirfc-ordered-list-v3>>).

[[source-asciirfc-unordered-list]]
.AsciiRFC With Unordered lists
====
[source,asciidoc]
----
* One
* Two
** Three
*** Four
** Five
* Six
----
====

[[source-asciirfc-unordered-list-v3]]
.AsciiRFC With Unordered Lists (RFC XML v3)
====
[source,xml]
----
<list style="symbols">
  <t>One</t>
  <t>Two</t>
  <t>Three</t>
  <t>Four</t>
  <t>Five</t>
  <t>Six</t>
</list>
----
====

[[source-asciirfc-ordered-list]]
.AsciiRFC With Ordered lists
====
[source,asciidoc]
----
[loweralpha]
. First
. Second
[upperalpha]
.. Third
.. Fourth
. Fifth
. Sixth
----
====

[[source-asciirfc-ordered-list-v3]]
.AsciiRFC With Ordered Lists (RFC XML v3)
====
[source,xml]
----
<ol anchor="id" type="a">
  <li>First</li>
  <li>
    <t>Second</t>
    <ol type="A">
      <li>Third</li>
      <li>Fourth</li>
    </ol>
  </li>
  <li>Fifth</li>
  <li>Sixth</li>
</ol>
----
====

[[source-asciirfc-definition-list]]
.AsciiRFC With Definition lists
====
[source,asciidoc]
----
RFC::
  Request For Comment, a type of publication from the Internet
  Engineering Task Force (IETF) and the Internet Society (ISOC)
RFC XML::
  An XML format for the publishing of RFCs, specified in RFC 7749 (v2)
  and RFC 7991 (v3)
----
====

[[source-asciirfc-definition-list-v3]]
.AsciiRFC With Definition Lists (RFC XML v3)
====
[source,xml]
----
<dl>
  <dt>RFC</dt>
  <dd>
    <t>Request For Comment, a type of publication from the Internet
    Engineering Task Force (IETF) and the Internet Society (ISOC)</t>
  </dd>
  <dt>RFC XML</dt>
  <dd>
    <t>An XML format for the publishing of RFCs, specified in RFC 7749
    (v2) and RFC 7991 (v3)</t>
  </dd>
</dl>
----
====


=== List Continuation

A list item by default spans a single paragraph. A following paragraph
or other block element can be appended to the current list item by
prefixing it with `+` in a separate line.

See the "List Continuation" section in <<Asciidoctor-Manual>> for more
information.

An example of list containuation with text is shown in
<<source-asciirfc-list-text>> with its rendered version in
<<source-asciirfc-list-text-v3>>.

[[source-asciirfc-list-text]]
.AsciiRFC List With Text Continuation
====
[source,asciidoc]
----
Notes::  Note 1.
+
Note 2.
+
Note 3.
----
====

[[source-asciirfc-list-text-v3]]
.AsciiRFC List With Text Continuation (RFC XML v3)
====
[source,xml]
----
<dl>
  <dt>Notes</dt>
  <dd>
    <t>Note 1.</t>
    <t>Note 2.</t>
    <t>Note 3.</t>
  </dd>
</dl>
----
====

(Multiple paragraphs are not permitted within a list item in RFC XML
v2.  The RFC XML converter deals with this by converting paragraph
breaks into line breaks within a list item.)

List continuations can also be embed to populate a list item with a
sequence of blocks as a unit (in an Asciidoctor syntax open block).

An example of list containuation with block is shown in
<<source-asciirfc-list-block>> with its rendered version in
<<source-asciirfc-list-block-v3>>.

[[source-asciirfc-list-block]]
.AsciiRFC List With Block Continuation
====
[source,asciidoc]
----
* List Entry 1
* List Entry 2
+
--
Note 2.

....
Literal
....

Note 3.
--
----
====

[[source-asciirfc-list-block-v3]]
.AsciiRFC List With Block Continuation (RFC XML v3)
====
[source,xml]
----
<ul>
  <li>List Entry 1</li>
  <li>
    <t>List Entry 2</t>
    <t>Note 2.</t>
    <figure>
      <artwork type="ascii-art">
        Literal
      </artwork>
    </figure>
    <t>Note 3.</t>
  </li>
</ul>
----
====

AsciiDoc, and thus AsciiRFC, considers paragraphs to be the basic
level of blocks, and does not permit lists to be nested within them:
text after a list is considered to be a new paragraph.

Therefore, markup as shown in <<source-asciirfc-list-impossible>>
cannot be generated via AsciiRFC.

[[source-asciirfc-list-impossible]]
.This RFC XML v3 Output Cannot Be Generated Using AsciiRFC
====
[source,xml]
----
<t>
  This is the start of a paragraph.
  <ul>
    <li>List Entry 1</li>
    <li>
      <t>List Entry 2</t>
      <t>Note 2.</t>
    </li>
  </ul>
  And this is the continuation of the paragraph.
</t>
----
====

