
== Notes And Asides

Asciidoctor supports a range of "admonitions", including notes,
warnings, and tips. They are indicated by a paragraph prefix (e.g.
`WARNING:`), or as a block with an admonition style attribute.

All admonitions are conflated in AsciiRFC, being converted to `note`
elements in the document preamble, and `cref` documents in the main
document.

This means that all admonitions will therefore not appear in the
textual output. A sample of this is shown in <<source-asciirfc-note>>
with its rendered output in <<source-asciirfc-note-v3>>.

[[source-asciirfc-note]]
.An AsciiRFC Adminition Block
======
[source,asciidoc]
----
== Section 1
[NOTE,source=GBS]
.Note Title
====
Any admonition inside the body of the text is a comment.
====
----
======

[[source-asciirfc-note-v3]]
.An AsciiRFC Adminition Block (RFC XML v3)
====
[source,xml]
----
<section anchor="_section_1" numbered="false">
  <name>Section 1</name>
  <t>
    <cref display="true" source="GBS">
      Any admonition inside the body of the text is a comment.
    </cref>
  </t>
</section>
----
====

With RFC XML v2, note that no inline formatting is permitted for
`cref` elements, and is therefore stripped for v2 by the converter.

Because paragraphs in AsciiRFC cannot contain any other blocks, a
comment at the end of a paragraph is treated as a new block. In the
document converter, any such comments are moved inside the preceding
RFC XML paragraph; if the comment is at the start of a section, as in
the example above, it is wrapped inside a paragraph.

The RFC XML v3 converter also supports `asides` (Asciidoctor
sidebars). A sample is shown in <<source-asciirfc-sidebar>> with its
rendered output in <<source-asciirfc-sidebar-v3>>.

[[source-asciirfc-sidebar]]
.An AsciiRFC Sidebar Block
====
[source,asciidoc]
----
== Section 1
****
Sidebar

Another sidebar

* This is a list

....
And this is ascii-art
....
****
----
====

[[source-asciirfc-sidebar-v3]]
.An AsciiRFC Sidebar Block Rendered As An Aside (RFC XML v3)
====
[source,xml]
----
<section anchor="_section_1" numbered="false">
  <name>Section 1</name>
  <aside>
    <t>Sidebar</t>
    <t>Another sidebar</t>
    <ul>
      <li>This is a list</li>
    </ul>
    <figure>
      <artwork type="ascii-art">
        And this is ascii-art
      </artwork>
    </figure>
  </aside>
</section>
----
====

Comments given in the AsciiDoc syntax (notated with initial `//`) are
not intended to be shown in the rendered output, and will not appear
in the output as XML comments.

