
== Notes And Asides

Asciidoctor syntax supports a range of "admonitions", including notes,
warnings, and tips. They are indicated by a paragraph prefix (e.g.
`WARNING:`), or as a block with an admonition style attribute.

All admonitions are conflated in AsciiRFC, being converted to `note`
elements in the document preamble, and `cref` documents in the main
document.

This means that all admonitions will therefore not appear in the
textual output, unless forced to through the `comments` processing
instruction. A sample admonition is shown in <<source-asciirfc-note>>
with its rendered output in <<source-asciirfc-note-v3>>.

[[source-asciirfc-note]]
.An AsciiRFC Adminition Block
======
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=note]
<CODE ENDS>
----
======

[[source-asciirfc-note-v3]]
.An AsciiRFC Adminition Block (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=note1]
<CODE ENDS>
----
====

With RFC XML v2, note that no inline formatting is permitted for
`cref` elements, and any such formatting is therefore stripped 
for v2 by the converter.

Because paragraphs in AsciiRFC cannot contain any other blocks, a
comment at the end of a paragraph is treated as a new block. In the
document converter, any such comments are moved inside the preceding
RFC XML paragraph; if the comment is at the start of a section, as in
the example above, it is wrapped inside a paragraph.

The RFC XML v3 converter also supports `asides` (Asciidoctor syntax
sidebars). A sample is shown in <<source-asciirfc-sidebar>> with its
rendered output in <<source-asciirfc-sidebar-v3>>.

[[source-asciirfc-sidebar]]
.An AsciiRFC Sidebar Block
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=aside]
<CODE ENDS>
----
====

[[source-asciirfc-sidebar-v3]]
.An AsciiRFC Sidebar Block Rendered As An Aside (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=aside1]
<CODE ENDS>
----
====

Comments given in the AsciiDoc syntax (notated with initial `//`) are
not intended to be shown in the rendered output, and will not appear
in the output as XML comments. XML comments can be generated by using
the `[comment]\#...#` inline formatting macro, or the `[.comment]` role
attribute on blocks. A sample is shown in <<source-asciirfc-sidebar>> with its
rendered output in <<source-asciirfc-sidebar-v3>>.

[[source-asciirfc-comment]]
.AsciiRFC delimited text intended as an XML Comment
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=comment]
<CODE ENDS>
----
====

[[source-asciirfc-comment-v3]]
.AsciiRFC delimited text Rendered As An XML Comment (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=comment1]
<CODE ENDS>
----
====

