== Inline Formatting

Like RFC XML v3, Asciidoctor supports italics, boldface, monospace, subscripts
and superscripts:

[source,asciidoc]
----
_Text_ *Text* `Text`  ^Superscript^ ~Subscript~
----

[source,xml]
----
<t><em>Text</em> <strong>Text</strong> <tt>Text</tt> 
<sup>Superscript</sup> <sub>Subscript</sub></t>
----

RFC XML v3 also supports tagging of BCP14 keywords <<RFC2119>>; this is done in
Asciidoctor either by tagging them with a custom formatting span 
(`bcp14#must not#`), or by converting BCP14 boldface all-caps words (unless the 
`:no-rfc-bold-bcp14: false` document attribute is set):

[source,asciidoc]
----
This [bcp14]#must not# stand

This *MUST NOT* stand
----

[source,xml]
----
<t>This <bcp14>MUST NOT</bcp14> stand</t>

<t>This <bcp14>MUST NOT</bcp14> stand</t>
----

Any spans of BCP14 text delimited by inline formatting delimiters needs to be
contained within a single line of text; the Asciidoctor API breaks up
formatting spans across line breaks.

[subs="quotes,attributes"]
Formatting delimiters like `\*` can be escaped with backslash (`\*`); double formatting
delimiters, like `{dblstar}` and `__`, need to be escaped with double backslash
(`\\**`). Escaping delimiters is not always reliable, and for double delimiters
it is preferable to use HTML entities (`&#42;&#42;`), or attribute references
(references to the value of attributes set in the document header):

[source,asciidoc]
----
:dblast: **

`{dblast}`
----

In extreme circumstances (such as quoting Asciidoc syntax), you may need to resort to
altering the substitutions behaviour within a given block of of Asciidoc; see
http://asciidoctor.org/docs/user-manual/#applying-substitutions

