== Inline Formatting

=== Italics, Boldface, Monospace, Subscripts, Superscripts

AsciiRFC supports italics, boldface, monospace, subscripts and
superscripts, just like RFC XML v3.

The inline formatting syntax given in <<source-asciirfc-inline>>
produces the RFC XML v3 output given in <<source-asciirfc-inline-v3>>.

[[source-asciirfc-inline]]
.Inline Formatting In AsciiRFC
====
[source,asciidoc]
----
_Text_ *Text* `Text`  ^Superscript^ ~Subscript~
----
====

[[source-asciirfc-inline-v3]]
.Inline Formatting In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<t><em>Text</em> <strong>Text</strong> <tt>Text</tt>
<sup>Superscript</sup> <sub>Subscript</sub></t>
----
====


=== Formatting BCP 14 Keywords

RFC XML v3 also supports tagging of BCP14 keywords <<RFC2119>>; this
is done in AsciiRFC either by tagging them with a custom formatting
span (`bcp14#must not#`), or by converting BCP14 boldface all-caps
words (unless the `:no-rfc-bold-bcp14: false` document attribute is
set).

Any spans of BCP14 text delimited by inline formatting delimiters
needs to be contained within a single line of text; the Asciidoctor
API breaks up formatting spans across line breaks.

This usage is demonstrated in <<source-asciirfc-bcp14>> with the
rendered output in <<source-asciirfc-bcp14-v3>>.

[[source-asciirfc-bcp14]]
.BCP14 Keywords In AsciiRFC
====
[source,asciidoc]
----
This [bcp14]#must not# stand

This *MUST NOT* stand
----
====

[[source-asciirfc-bcp14-v3]]
.BCP14 Keywords In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<t>This <bcp14>MUST NOT</bcp14> stand</t>

<t>This <bcp14>MUST NOT</bcp14> stand</t>
----
====


=== Escaping AsciiRFC Syntax

[subs="quotes,attributes"]
Formatting delimiters like `\*` can be escaped with backslash (`\*`);
double formatting delimiters, like `{dblstar}` and `__`, need to be
escaped with double backslash (`\\**`).

Escaping delimiters is not always reliable, and for double delimiters
it is preferable to use HTML entities (`&#42;&#42;`), or attribute
references (references to the value of attributes set in the document
header) as shown in <<source-asciirfc-escaping>>.

[[source-asciirfc-escaping]]
.Escaping Syntax In AsciiRFC
====
[source,asciidoc]
----
:dblast: **

`{dblast}`
----
====

In extreme circumstances (such as quoting AsciiDoc syntax), you may
need to resort to altering the substitutions behaviour within a given
block of of AsciiDoc; see the "Applying Substitutions" section of
<<Asciidoctor-Manual>>.

