== Inline Formatting

=== Italics, Boldface, Monospace, Subscripts, Superscripts

AsciiRFC supports italics, boldface, monospace, subscripts and
superscripts, just like RFC XML v3.

The inline formatting syntax given in <<source-asciirfc-inline>>
produces the RFC XML v3 output given in <<source-asciirfc-inline-v3>>.

[[source-asciirfc-inline]]
.Inline Formatting In AsciiRFC
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=inline_formatting]
<CODE ENDS>
----
====

[[source-asciirfc-inline-v3]]
.Inline Formatting In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=inline_formatting1]
<CODE ENDS>
----
====


=== Formatting BCP 14 Keywords

RFC XML v3 also supports tagging of BCP14 keywords <<RFC2119>>; this
is done in AsciiRFC either by tagging them with a custom formatting
span (`bcp14#must not#`), or by converting BCP14 boldface all-caps
words (unless the `:no-rfc-bold-bcp14: false` document attribute is
set).

Any spans of BCP14 text delimited by inline formatting delimiters
needs to be contained within a single line of text; in Asciidoctor
syntax, formatting spans are broken up across line breaks.

This usage is demonstrated in <<source-asciirfc-bcp14>> with the
rendered output in <<source-asciirfc-bcp14-v3>>.

[[source-asciirfc-bcp14]]
.BCP14 Keywords In AsciiRFC
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=bcp14]
<CODE ENDS>
----
====

[[source-asciirfc-bcp14-v3]]
.BCP14 Keywords In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=bcp14_1]
<CODE ENDS>
----
====


=== Escaping AsciiRFC Syntax

[subs="quotes,attributes"]
Formatting delimiters like `\*` can be escaped with backslash (`\*`);
double formatting delimiters, like `{dblstar}` and `__`, need to be
escaped with double backslash (`\\**`).

Escaping delimiters is not always reliable, and for double delimiters
it is preferable to use HTML entities (`&#42;&#42;`), or attribute
references (references to the value of attributes set in the document
header) as shown in <<source-asciirfc-escaping>>.

[[source-asciirfc-escaping]]
.Escaping AsciiRFC Syntax Using Attributes
====
[source,asciidoc]
----
<CODE BEGINS>
:dblast: **

`{dblast}`
<CODE ENDS>
----
====

In extreme circumstances (such as quoting AsciiDoc syntax), you may
need to resort to altering the substitutions behaviour within a given
block of of AsciiDoc; see the "Applying Substitutions" section of
<<Asciidoctor-Manual>>.

