
== Cross-References

=== Basic Referencing

Anchors for cross-references are notated as `[[...]]` or `[#...]`, and
can be inserted on their own line in front of most blocks.

Asciidoctor syntax supports anchors in a much wider range of contexts
than is supported than RFC XML v3 (let alone v2); anchors that are not
supported for that version of RFC XML are simply ignored by the
converter. 

Note that anchors in RFC XML are constrained to the format
`[A-Za-z_:][[A-Za-z0-9_:.-]*` (i.e. `xsd:ID`).

[subs="quotes"]
Cross-references to anchors are notated as `<<...>>`; cross-references
with custom text as `<<reference,text>>`.

An example of using cross-references in AsciiRFC is given in
<<source-asciirfc-xref>> with its rendered output in
<<source-asciirfc-xref-v3>>.

[[source-asciirfc-xref]]
.Setting And Referring To Cross-References In AsciiRFC
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=xref]
<CODE ENDS>
----
====

[[source-asciirfc-xref-v3]]
.Setting And Referring To Cross-References In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=xref1]
<CODE ENDS>
----
====

=== Referencing With Attributes

While Asciidoctor syntax natively does not support attributes on
cross-references, AsciiRFC works around that by embedding formatting
information as templated text within cross-references:

* `format=x: text` populates the `xref@format` attribute

* a section number followed by one of the words `of`, `parens`,
  `bare`, `text` is treated as a `relref` reference to an external
  document.

An example of referencing with attributes is given in
<<source-asciirfc-xref-att>> with its output in
<<source-asciirfc-xref-att-v3>>.


[[source-asciirfc-xref-att]]
.Cross-References With Attributes In AsciiRFC
====
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=relref]
<CODE ENDS>
----
====

[[source-asciirfc-xref-att-v3]]
.Cross-References With Attributes In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=relref1]
<CODE ENDS>
----
====

=== Indexing

Inline index entries are notated as `\((...))`. Index entries
which do not appear in the text are notated as `\(((...)))`;
such entries may include a separate sub-entry, separated from
the main entry by comma.

[[source-asciirfc-index]]
.AsciiRFC Index Entries
======
[source,asciidoc]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=index]
<CODE ENDS>
----
======

[[source-asciirfc-index-v3]]
.AsciiRFC Index Entries (RFC XML v3)
====
[source,xml]
----
<CODE BEGINS>
include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=index1]
<CODE ENDS>
----
====

