
[#cross-references]
== Cross-References

=== Basic Referencing

Anchors for cross-references are notated as `[[...]]` or `[#...]`, and
can be inserted on their own line in front of most blocks.

Asciidoctor syntax supports anchors in a much wider range of contexts
than is supported than RFC XML v3 (let alone v2); anchors that are not
supported for that version of RFC XML are simply ignored by the
converter. 

Note that anchors in RFC XML are constrained to the format
`[A-Za-z_:][[A-Za-z0-9_:.-]*`.

[subs="quotes"]
Cross-references to anchors are notated as `<<...>>`; cross-references
with custom text as `<<reference,text>>`.

An example of using cross-references in AsciiRFC is given in
<<source-asciirfc-xref>> with its rendered output in
<<source-asciirfc-xref-v3>>.

[[source-asciirfc-xref]]
.Setting And Referring To Cross-References In AsciiRFC
====
[source,asciidoc]
----
[[cross-reference]]
== Section 1

== Section 2
See <<cross-reference>>.

== Section 3
See <<cross-reference,text>>
----
====

[[source-asciirfc-xref-v3]]
.Setting And Referring To Cross-References In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<section anchor="cross-reference" numbered="false">
  <name>Section 1</name>
</section>
<section anchor="_section_2" numbered="false">
  <name>Section 2</name>
  <t>
    See
    <xref target="cross-reference">
    </xref>.
  </t>
</section>
<section anchor="_section_3" numbered="false">
  <name>Section 3</name>
  <t>
    See
    <xref target="cross-reference">
      text
    </xref>
  </t>
</section>
----
====

=== Referencing With Attributes

While Asciidoctor syntax natively does not support attributes on
cross-references, AsciiRFC works around that by embedding formatting
information as templated text within cross-references:

* `format=x: text` populates the `xref@format` attribute

* a section number followed by one of the words `of`, `parens`,
  `bare`, `text` is treated as a `relref` reference to an external
  document.

An example of referencing with attributes is given in
<<source-asciirfc-xref-att>> with its output in
<<source-asciirfc-xref-att-v3>>.


[[source-asciirfc-xref-att]]
.Cross-References With Attributes In AsciiRFC
====
[source,asciidoc]
----
== Section 4
See <<cross-reference,format=counter: text>>

== Section 5
See <<cross-reference,format=title>>

See <<cross-reference,1.3 of>>
<<cross-reference,1.4 comma: text>>
<<cross-reference#fragment1,2.5.3 parens>>
<<cross-reference#fragment2,6.2a bare: text>>
----
====

[[source-asciirfc-xref-att-v3]]
.Cross-References With Attributes In AsciiRFC (RFC XML v3)
====
[source,xml]
----
<section anchor="_section_4" numbered="false">
  <name>Section 4</name>
  <t>
    See
    <xref format="counter" target="cross-reference">
      text
    </xref>
  </t>
</section>
<section anchor="_section_5" numbered="false">
  <name>
    Section 5
  </name>
  <t>
    See
    <xref format="title" target="cross-reference" />
  </t>
  <t>
    See
    <relref section="1.3" displayformat="of"
     target="cross-reference" />
    <relref section="1.4" displayformat="comma"
     target="cross-reference">
      text
    </relref>
    <relref relative="fragment1" section="2.5.3"
     displayformat="parens" target="cross-reference" />
    <relref relative="fragment2" section="6.2a"
     displayformat="bare" target="cross-reference">
      text
    </relref>
  </t>
</section>
----
====

