== Bibliography

The simple encoding of bibliography syntax provided by AsciiDoc (and
Asciidoctor syntax) is inadequate for the complexity of bibliographic
markup required by RFC XML.

RFC documents overwhelmingly cite other RFC documents, and canonical
RFC XML bibliographic entries are available at <<IETF-BibXML>>; so it
would be inefficient to encode those entries natively in AsciiRFC, only to have
them converted back to RFC XML.

The converter provides two means of incorporating bibliographies into
RFC documents authored in AsciiRFC:

* using raw RFC XML; and

* assembling bibliographies in preprocessing.

In either case, the RFC XML needs to be well-formed; missing closing
tags can lead to erratic behaviour in the converter.

=== Using Raw RFC XML

In the first method, bibliographic citations are handled like all
other AsciiRFC cross-references. The bibliographic entries for
normative and informative references are given in the AsciiRFC as
passthrough blocks, which contain the raw RFC XML for all references;
document conversion leaves the raw RFC XML in place. 

This approach requires authors to maintain the normative and
informative bibliographies within the document, to update them as
citations are added and removed, and to sort them manually. However,
if the citation is stored on the IETF's RFC XML citation libraries
(see https://xml2rfc.tools.ietf.org), AsciiRFC will automatically
replace it with an external reference to that citation. So the body of
the citation XML can be left out.

For example, the AsciiRFC in <<source-bib-asciirfc-inline>> will
generate the corresponding RFC XML v3 output in <<source-bib-xml-inline>>.

[[source-bib-asciirfc-inline]]
.AsciiRFC Inline Bibliography 
====
[source,asciidoc]
----
  <CODE BEGINS>
  include::../examples/rfc-camelot-holy-grenade/draft-camelot-holy-grenade.adoc[tag=bibliography]
  <CODE ENDS>
----
====

[[source-bib-xml-inline]]
.AsciiRFC Inline Bibliography Rendered As RFC XML v3
====
[source,xml]
----
  <CODE BEGINS>
  include::../examples/rfc-camelot-holy-grenade/xml3/draft-camelot-holy-grenade.xml[tag=bibliography1]
  <CODE ENDS>
----
====

[[asciidoctor_bibliography]]
=== Preprocessing Using "asciidoctor-bibliography"

The alternative method is to use a preprocessing tool,
<<asciidoctor-bibliography>>, to import citations into the AsciiRFC
document from an external file of references.

The references file consists of RFC XML reference entries, and still
needs to be managed manually; however the bibliographies are assembled
from that file, sorted, and inserted into the normative and
informative references in preprocessing. Citations in the document
itself are given as macros to be interpreted by the preprocessor; this
allows them to be split into normative and informative references.
(The MMark tool likewise splits reference citations into normative and
informative.)

Integration with the `asciidoc-bibliography` gem proceeds as follows:

. Create an RFC XML references file, consisting of a `<references>`
element with individual `<reference>` elements inserted, as would be
done for the informative and normative references normally. The
references file will contain all possible references to be used in the
file; the bibliography gem will select which references have actually
been cited in the document.

.. Rather than hand crafting RFC XML references for RFC documents, you
should download them from an authoritative source; e.g.,
`\http://xml.resource.org/public/rfc/bibxml/reference.RFC.2119.xml`.
Note that RFC XML references from this link contains the XML
document declaration, which needs to be removed before being used in
the XML bibliography.

.. Unlike the case for RFC XML documents created manually, the
references file does not recognise XML entities and will not attempt
to download them during processing.  Any references to
`\http://xml.resource.org/public/rfc/bibxml/` will need to be
downloaded and inserted into the references file.

.. The RFC XML in the references file will need to be appropriate to
the version of RFC XML used in the main document, as usual. Note that
RFC XML v2 references are forward compatible with v3; v3 contains a
couple of additional elements.

. Add to the main document header attributes referencing the
references file (`:bibliography-database:`), and the bibliography
style (`:bibliography-style: rfc-v3`).

. References to a normative reference are inserted with the macro
`cite:norm[id]` instead of pass:q[`<<id>>`], where `id` is the anchor
of the reference.

. References to an informative reference are inserted with the macro
`cite:info[id]` instead of pass:q[`<<id>>`], where `id` is the anchor
of the reference.

. Formatted crossreferences and `relref` crossreferences are entered
by inserting the expected raw XML in the `text` attribute. Do not use
the `{cite}` interpolation of the citation.  For example:

** pass:q[`<<id,words>>`] = `cite:norm[id, text="<xref target='id'>words</xref>"]`

** pass:q[`<<id,format=counter: words>>`] (processed as a formatted cross-reference) =
  `cite:norm[id, text="<xref format='counter' target='id'>words</xref>"]`

** pass:q[`<<id,2.4 comma: words>>`] (processed as relref) =
  `cite:norm[id, text="<relref displayFormat='comma' section='2.4' target='id'}/>"]`

** pass:q[`<<id#section2_4,2.4 comma: words>>`]
  (processed as relref with a cross-document internal reference) =
  `cite:norm[id, text="<relref relative='section2_4' displayFormat='comma' section='2.4' target='id'/>"]`


. Normative and Informative References are inserted in the document
through a macro, which occurs where the RFC XML references would be
inserted, as shown in <<source-bib-abib>>.

[[source-bib-abib]]
.Using asciidoctor-bibliography For Bibliography Preprocessing
====
[source,asciidoc]
----
<CODE BEGINS>
[bibliography]
== Normative References

++++
bibliography::norm[]
++++

[bibliography]
== Informative References

++++
bibliography::info[]
++++
<CODE ENDS>
----
====

