== Bibliography

Asciidoctor natively has a simple encoding of bibliographies, which is not
adequate for the complexity of bibliographic markup required by RFC XML.

RFC documents overwhelmingly cite other RFC documents, and canonical RFC XML
bibliographic entries are available at <<IETF-BibXML>>; so it would be
inefficient to encode those entries in AsciiRFC, only to have them converted
back to RFC XML.

The converter provides two means of incorporating bibliographies into RFC
documents authored in AsciiRFC:

* using raw RFC XML; and

* assembling bibliographies in preprocessing.

In either case, the RFC XML needs to be well-formed; missing closing tags can
lead to erratic behaviour in the converter.

=== Using Raw RFC XML

In the first method, bibliographic citations are handled like all other
AsciiRFC cross-references. The bibliographic entries for normative and
informative references are given in the AsciiRFC as passthrough blocks, which
contain the raw RFC XML for all references; document conversion leaves the raw
RFC XML in place. This approach requires authors to maintain the normative and
informative bibliographies within the document, to update them as citations are
added and removed, and to sort them manually. For example:

[source,asciidoc]
----
Some datagram padding may be needed.<<RFC7253>>

[bibliography]
== Normative References
++++
<reference anchor='RFC7253'
  target='https://tools.ietf.org/html/rfc7253'>
  <front>
    <title>Guidelines for Writing an IANA Considerations
      Section in RFCs</title>
    <author initials="T." surname="Krovetz">
      <organization>Sacramento State</organization>
    </author>
    <author initials="P." surname="Rogaway">
      <organization>UC Davis</organization>
    </author>
    <date month='May' year='2014'/>
  </front>
  <seriesInfo name="RFC" value="7253"/>
</reference>
++++
----

[source,xml]
----
<t>Some datagram padding may be needed <xref target="RFC7253"/></t>

</middle><back>
<references anchor="_references">
<name>Normative References</name>
<reference anchor='RFC7253'
  target='https://tools.ietf.org/html/rfc7253'>
  <front>
    <title>Guidelines for Writing an IANA Considerations
      Section in RFCs</title> <author initials="T." surname="Krovetz">
      <organization>Sacramento State</organization>
    </author>
    <author initials="P." surname="Rogaway">
      <organization>UC Davis</organization>
    </author>
    <date month='May' year='2014'/>
  </front>
  <seriesInfo name="RFC" value="7253"/>
</reference>
</references>
----

[#asciidoctor_bibliography]
=== Using preprocessing

The alternative method is to use a preprocessing tool,
<<asciidoctor-bibliography>>, to import citations into the AsciiRFC document from
an external file of references.

The references file consists of RFC XML reference entries, and still needs to
be managed manually; however the bibliographies are assembled from that file,
sorted, and inserted into the normative and informative references in
preprocessing. Citations in the document itself are given as macros to be
interpreted by the preprocessor; this allows them to be split into normative
and informative references. (The MMark tool likewise splits reference citations
into normative and informative.)

Integration with the asciidoc-bibliography gem proceeds as follows:

. Create an RFC XML references file, consisting of a `<references>` element
with individual `<reference>` elements inserted, as would be done for the
informative and normative references normally. The references file will contain
all possible references to be used in the file; the bibliography gem will
select which references have actually been cited in the document.

.. Rather than hand crafting RFC XML references for RFC documents, you should
download them from an authoritative source; e.g.
`http://xml.resource.org/public/rfc/bibxml/reference.RFC.2119.xml`

.. Unlike the case for RFC XML documents created manually, the references file
does not recognise XML entities and will not attempt to download them during
processing.  Any references to `http://xml.resource.org/public/rfc/bibxml/` will
need to be downloaded and inserted into the references file.

.. The RFC XML in the references file will need to be appropriate to the
version of RFC XML used in the main document, as usual. Note that RFC XML v2
references are forward compatible with v3; v3 contains a couple of additional
elements.

. Add to the main document header attributes referencing the references file
(`:bibliography-database:`), and the bibliography style (`:bibliography-style:
rfc-v3`).

. References to a normative reference are inserted with the macro
`cite:norm[id]` instead of pass:q[`<<id>>`], where `id` is the anchor of the
reference.

. References to an infomrative reference are inserted with the macro
`cite:info[id]` instead of pass:q[`<<id>>`], where `id` is the anchor of the
reference.

. Formatted crossreferences and `relref` crossreferences are entered by
inserting the expected raw XML in the `text` attribute. Do not use the `{cite}`
interpolation of the citation.  For example:

** pass:q[`<<id,words>>`] = `cite:norm[id, text="<xref target='id'>words</xref>"]`

** pass:q[`<<id,format=counter: words>>`] (processed as a formatted crossreference) =
  `cite:norm[id, text="<xref format='counter' target='id'>words</xref>"]`

** pass:q[`<<id,2.4 comma: words>>`] (processed as relref) =
  `cite:norm[id, text="<relref displayFormat='comma' section='2.4' target='id'}/>"]`

** pass:q[`<<id#section2_4,2.4 comma: words>>`]
  (processed as relref with a cross-document internal reference) =
  `cite:norm[id, text="<relref relative='section2_4' displayFormat='comma' section='2.4' target='id'/>"]`


. Normative and Informative References are inserted in the document through a
macro, which occurs where the RFC XML references would be inserted:

[source,asciidoc]
--
[bibliography]
== Normative References

++++
bibliography::norm[]
++++

[bibliography]
== Informative References

++++
bibliography::info[]
++++
--

