== Authoring

To author an AsciiRFC document, you should first familiarise yourself
with the <<Asciidoctor-Manual>>.

The <<asciidoctor-rfc>> Ruby gem source code distribution also has
samples of individual RFC XML features in v2 and v3, and examples of
self-standing AsciiRFC documents, along with their RFC XML renderings.
(This includes round-tripped RFC XML documents.)


=== Using the "rfc-in-asciidoc-template"

In addition, you can clone the sample `rfc-in-asciidoc-template`
repository as a template, and populate it for your AsciiRFC document
using the steps shown in <<source-asciirfc-sample-template>>.

[[source-asciirfc-sample-template]]
.Cloning The AsciiRFC Document Template
====
[source,console]
----
$ git clone https://github.com/riboseinc/rfc-in-asciidoc-template
----
====

=== Installing AsciiRFC Backend Processors

Converting your AsciiRFC to RFC XML is a simple as installing the
Asciidoctor Ruby gem `asciidoctor` (see "Installation" at
<<Asciidoctor>>) and the `asciidoctor-rfc` gem in Ruby (through
RubyGems), then running the `asciidoctor` executable on the document,
specifying the `asciidoctor-rfc` gem as a library.

The necessary steps are shown in <<source-asciirfc-install-converters>>.

[[source-asciirfc-install-converters]]
.Installing The AsciiRFC Backend Processors
====
[source,console]
----
$ gem install asciidoctor-rfc
$ asciidoctor -b rfc3 -r 'asciidoctor-rfc' foo.adoc  # RFC XML v3 output
$ asciidoctor -b rfc2 -r 'asciidoctor-rfc' foo.adoc  # RFC XML v2 output
----
====


=== Iterating AsciiRFC Content

As you author AsciiRFC content, you should iterate by running the
AsciiRFC conversion frequently, to ensure that you are still
generating valid XML through your markup. The converter makes an
effort to ensure that its XML output is valid, and it issues warnings
about likely issues; it also validates its own XML output against the
RFC XML schema (of the corresponding version), and reports errors in
the XML output in the format shown in
<<source-asciirfc-schema-error>>.

[[source-asciirfc-schema-error]]
.Sample Validation Error Message From AsciiRFC
====
[source,console]
----
V3 RELAXNG Validation: 12:0: ERROR: Invalid attribute
  sortRefs for element rfc
----
====

Note that validation against the RELAXNG RFC XML schema includes
confirming the referential integrity of all cross-references in the
document.

It may be necessary to intervene in the XML output generated by the
converter, either because the block model of AsciiRFC does not conform
with the intended RFC XML (e.g. lists embedded in paragraphs), or
because RFC XML features are required that are not supported within
AsciiRFC.

