== Authoring

To author an AsciiRFC document, you should familiarise yourself with the
http://asciidoctor.org/docs/user-manual[Asciidoctor specification]. The
converter Ruby gem source code distribution also has
https://github.com/riboseinc/asciidoctor-rfc/tree/master/spec/asciidoctor/rfc[samples of individual RFC XML features], in v2 and v3, and
https://github.com/riboseinc/asciidoctor-rfc/tree/master/spec/examples[examples of self-standing AsciiRFC documents], 
along with their RFC XML renderings. (This includes round-tripped RFC XML
documents.)

In addition, you can clone the sample `rfc-in-asciidoc-template` repository as
a template, and populate it for your AsciiRFC documents:

[source,console]
----
$ git clone https://github.com/riboseinc/rfc-in-asciidoc-template
----

Converting your AsciiRFC to RFC XML is a simple as installing Asciidoctor (see
http://asciidoctor.org/#installation) and the `asciidoctor-rfc` gem in Ruby, then
running the asciidoctor executable on the document, specifying the
asciidoctor-rfc gem as a library:

[source,console]
----
$ git clone https://github.com/riboseinc/asciidoctor-rfc.git
$ cd asciidoctor-rfc
$ bundle install
$ gem build asciidoctor-rfc.gemspec
$ gem install asciidoctor-rfc
$ asciidoctor -b rfc3 -r 'asciidoctor-rfc' a.adoc  # RFC XML v3 output
$ asciidoctor -b rfc2 -r 'asciidoctor-rfc' a.adoc  # RFC XML v2 output
----

As you author AsciiRFC content, you should iterate through running the
Asciidoctor conversion frequently, to ensure that you are still generating
valid XML through your markup. The converter makes an effort to ensure that its
XML output is valid, and it issues warnings about likely issues; it also
validates its own XML output against the Asciidoctor schema, and reports errors
in the XML output in the following format:

[source,console]
----
V3 RELAXNG Validation: 12:0: ERROR: Invalid attribute 
  sortRefs for element rfc
----

Note that validation against the RELAXNG RFC XML schema includes confirming the
referential integrity of all cross-references in the document.

It may be necessary to intervene in the XML output generated by the converter,
either because the block model of AsciiRFC does not conform with the
intended RFC XML (e.g. lists embedded in paragraphs), or because RFC XML
features are required that are not supported within AsciiRFC.

