
== Security Considerations

* Ensure your AsciiRFC generator comes from a geniune and trustworthy
source.  This protects your own machine and also prevents injection of
malicious content in your resulting document.

* An AsciiRFC generator may cause errors in textual rendering or link
generation that may lead to security issues.

* Creating cross-references (and also bibliographic references) to
external documents may pose risks since the specified external
location may become controlled by a malicious party.

* URIs that start with the "http:" or "https:" prefix are
automatically converted into links in AsciiRFC except when escaped
with a backslash before the prefix. A URI that is intended to be text
but unintentionally rendered as a link may cause users to visit a
malicious website with security consequences.

* AsciiRFC contains syntax that can directly incorporate remote URI
content, such as `include::` which allows remotely-located AsciiRFC
content files.  If a remote URI contains malicious content, this
content will be included in the resulting AsciiRFC document compiled
as RFC XML.  Remotely-linked URIs should always be checked for
malicious content prior to compiling AsciiRFC into RFC XML.

