= An API For Calendar-Based Fortune Heuristics Services
Gabriel Destiny; Charise Luck
:doctype: internet-draft
:abbrev: Calendar Fortune Heuristics API
:name: draft-divination-cfapi-00
:status: informational
:ipr: trust200902
:area: Internet
:submission-type: independent
:intended-series: informational
:revdate: 2018-04-01T00:00:00Z
:lastname: Destiny
:fullname: Gabriel Destiny
:forename_initials: G.
:organization: Divination Inc.
:email: gabriel.destiny@example.com
:street: 9288 N Divine Street
:city: Dunn
:code: 28334
:region: NC
:country: USA
:lastname_2: Luck
:fullname_2: Charise Luck
:forename_initials_2: C.
:organization_2: Divination Inc.
:email: charise.luck@example.com
:street_2: 9288 N Divine Street
:city_2: Dunn
:code_2: 28334
:region_2: NC
:country_2: USA

//TODO change name:
//BELIEF: Beacons of Life, and Significant Intervals or Events in near Future

[abstract]

This document describes a JSON HTTP API for online services that
provide calendar-based fortune heuristics.

// No references allowed in the Abstract


== Introduction

Fortune-telling, the practice of predicting information about a
person's life, is an activity practiced throughout history.

While there are myriad forms of fortune telling methodologies, this
document applies to a particular form of service that provides fortune
heuristics, commonly known as "luck", for a particular subject based
on a calendar-based input.

Since HTTP <<RFC7230>> status codes are insufficient to convey
information about fortune heuristics, this specification defines a
simple JSON <<RFC8259>> document format for this purpose. The
response can be used by HTTP APIs to deliver results to non-human
clients or to an end-user.


== Conventions Used in This Document

The key words "**MUST**", "**MUST NOT**", "**REQUIRED**", "**SHALL**",
"**SHALL NOT**", "**SHOULD**", "**SHOULD NOT**", "**RECOMMENDED**",
"**MAY**", and "**OPTIONAL**" in this document are to be interpreted
as described in <<RFC2119>>.

Well-known URI:: This specification makes use of the "well-known URI"
feature of HTTP servers <<RFC5785>> to provide a bootstrapping URI for
the client usage of fortune heuristics services.

Root of Fortune:: The service discovery endpoint that provides a URI
list of available fortune heuristic endpoints available, in accordance
with <<service-discovery>>.

== Fortune Heuristics Service Well-Known URI

A well-known URI called "fortune" is registered by this specification
for fortune heuristics services (see <<iana>>).

Services complying with this document **SHOULD** have its well-known
URI pointing (directly or through redirection) to the Root of Fortune.

The Root of Fortune can be used by the client for service discovery,
namely, the available calendar-based fortune heuristics services
available on the server, as specified in <<service-discovery>>.

=== Well-Known URI Redirection

Servers **MUST** redirect HTTP requests for that resource to the
actual "context path" using one of the available mechanisms provided
by HTTP <<RFC7230>> (e.g., using a 301, 303, or 307 response).

Clients **MUST** handle HTTP redirects on the well-known URI.

=== Well-Known URI Cache Behavior

Servers **SHOULD** set an appropriate Cache-Control header value (as
according to <<RFC7234,5.2 of>>) in the redirect response to set
caching behavior as required by the type of response generated.

// TODO: rewrite the following paragraphs
////

Given available service paths may differ from user to user, the server
**MAY** require authentication when a client tries to access the
".well-known" URI (i.e., the server would return a 401 status response
to the unauthenticated request from the client, then return the
redirect response only after a successful authentication by the
client).

=== Example: Well-Known URI Redirects to Actual Fortune Heuristics Service Path

A CalDAV server has a "context path" that is "/servlet/caldav".  The
client will use "/.well-known/caldav" as the path for its
"bootstrapping" process after it has first found the FQDN and port
number via an SRV lookup or via manual entry of information by the
user, from which the client can parse suitable information.  When the
client makes an HTTP request against "/.well-known/caldav", the server
would issue an HTTP redirect response with a Location response header
using the path "/servlet/caldav".  The client would then "follow" this
redirect to the new resource and continue making HTTP requests there
to complete its "bootstrapping" process.
////


== New HTTP Methods: SEEK and DIVINE

This specification defines two new HTTP methods: "SEEK" and "DIVINE"
methods for HTTP <<RFC7230>>.

While HTTP GET requests are treated equivalently as the "SEEK" and
"DIVINE" requests, its usage is discouraged and therefore **SHOULD
NOT** be used.

Usage of these methods are defined in the sections below.


== Defined Data Types: Date-Time Formats

This specification defines a number of date-time formats as according
to the conventions of <<RFC3339>> for the unambiguous communication
between client and server.

The types defined are as follows.

`DATETIME`::
  As described in <<RFC3339,5.6 of>>, with the addition that reduced
  accuracy representations described in <<ISO.8601-1.2018>> are
  supported.  Reduced accuracy date and times are accepted where a
  date or time component (2-digits long) is replaced by "--".
+
For example, the date time "2018-04---T01:02:00Z" represents the UTC
time of 1:02am, on an unknown day within April of the year 2018.

`DATE`::
  As described in "DATETIME", but the "time" component will not be
  taken into account in the algorithm.


[#service-discovery]
== Fortune Heuristics Service Discovery

[#root-of-fortune]
=== Root of Fortune Path URI ("/")

The Root of Fortune URI, defined as "/" in this document, is used for
service discovery on types of calendar-based fortune heuristics
available.

An empty SEEK request with the "application/json" request type
**MUST** be sent to this endpoint to retrieve the available endpoints.
All other HTTP methods **MUST NOT** be supported at this URI.

An example of such a response is as follows:

[source,json]
----
HTTP/1.1 200 Success
Content-Type: application/json
Content-Language: en

{
  "diviners" : [
    "/astrology",
    "/bazi",
  ]
}
----

A service discovery object **MUST** have the following members:

`diviners`::
  (JSON array)
  An array that contains endpoints that conform to this specification.
  All endpoints listed here are relative to the Root of Fortune path.
  For example, the path "/astrology" listed in the example has an
  endpoint path of "[root-of-fortune]/astrology", where
  "[root-of-fortune]" indicates the real path of the Root of Fortune.

[#service-endpoint]
== Fortune Heuristics Service Endpoint

An endpoint offering fortune heuristics services must adhere to 
specifications in this section.

[#endpoint-specification-request]
=== Service Specification Request

To retrieve capabilities and parameters of an endpoint complying with
this specification, a service specification JSON object is returned.

An empty SEEK request with the "application/json" request type
**MUST** be sent to this endpoint to retrieve the service
specification that describes parameters accepted by this endpoint.

Two examples of such a response are given below.

[source,json]
----
HTTP/1.1 200 Success
Content-Type: application/json
Content-Language: en

{
  "description": "Gaze into your upcoming luck!",
  "details": "https://divination.example.com/manual/astrology-api",
  "parameters": {
    "birthday": {
      "type": "DATE",
      "description": "Your birth date in UTC"
    },
    "targetDateBegin": {
      "type": "DATE",
      "description": "The start of the target date range to report on"
    },
    "targetDateEnd": {
      "type": "DATE",
      "description": "The end of the target date range to report on"
    },
    "interval": {
      "values": {
        "D": "Daily",
        "M": "Monthly",
        "Y": "Yearly"
      }
      "description": "Available intervals to report on."
    }
  }
}
----

[source,json]
----
HTTP/1.1 200 Success
Content-Type: application/json
Content-Language: en

{
  "description": "Matches and mis-matches according to the "
    "Yin Yang and Five Elements techniques",
  "details": "https://divination.example.com/manual/bazi-api",
  "parameters": {
    "birthday": {
      "type": "DATETIME",
      "description": "Your birth date and time in UTC"
    },
    "targetDateBegin": {
      "type": "DATETIME",
      "description": "The start of the target date/time range to report on"
    },
    "targetDateEnd": {
      "type": "DATETIME",
      "description": "The end of the target date/time range to report on"
    },
    "interval": {
      "values": {
        "H": "Hourly",
        "D": "Daily",
        "M": "Monthly",
        "Y": "Yearly"
      }
      "description": "Available intervals to report on."
    }
  }
}
----

[#service-endpoint-specification]
=== Members Of A Service Discovery Object

A service discovery object **MUST** contain the following members.

`description`::
  (string) A short, human-readable summary of the fortune heuristic
  service at this endpoint. This **SHOULD** be a stable reference.

`details`::
  (URI, optional) A URI reference that provides further details for human
  consumption, such as API documentation that includes details of
  parameters accepted or response states.
  
`parameters`::
  (object, mandatory) An object that specifies what parameters
  are accepted by this endpoint. Each parameter key within this object
  specifies an accepted parameter name, and its value is a parameter
  specification object, which is described below.
  
A parameter specification object **SHOULD** contain the following
members:

`type`::
  (string, optional) The value type accepted by this parameter. Value
  types are described in this document. This member is mutually
  exclusive with `values`.

`description`::
  (string, mandatory) The purpose of this parameter.

`values`::
  (object, optional) The accepted values of this parameter, unlisted
  values **SHOULD** not be accepted by the parameter. Each key within
  this object specifies an accepted value, and its value provides a
  description of the purpose of the value.


[#endpoint-report]
== Fortune Heuristics Report Request and Response

[#endpoint-report-request]
=== Fortune Heuristics Report Request

A request using the HTTP "DIVINE" method and the "application/json"
type **MUST** be sent to the fortune heuristic endpoint to retrieve
results for a fortune heuristic query.

The request made **MUST** conform to the specifications of the
endpoint, as retrieved via the "SEEK" method described in
<<endpoint-specification-request>>.

An example of a request is provided below.

[source]
----
URI: /divination/astrology
Method: DIVINE
Content-Type: application/json
Content-Language: en

{
  "birthday": "1976-02-11T00:00:00Z",
  "targetDateBegin": "2018-01-01T00:00:00Z"
  "targetDateEnd": "2019-01-01T00:00:00Z"
  "interval": "M"
}
----


[#endpoint-report-response]
=== Fortune Heuristics Report Response

A fortune heuristic query using the "DIVINE" method triggers a
response that contains a fortune heuristics report.

A successful response returns a JSON object that **MUST** conform
to the object structure described in this section.

A report object **SHOULD** contain the following members:

`type`::
  (URI, mandatory) A URI that defines the type of the report located
  at the `report` key of this object.

`report`::
  (object, mandatory) An object that contains two keys, `intervals`
  and `events`. The `intervals` object contains an array of interval
  objects that matches the demanded intervals in the request within
  the target date range.
  The `events` object contains an array of significant event objects
  within the target date range.


An example of a response is provided below.

[source]
----
URI: /divination/astrology
Method: DIVINE
HTTP/1.1 200 Success
Content-Type: application/json
Content-Language: en

{
  "type": "https://association-of.astrology/reports/monthly",
  "report": {
    "intervals": [
      {
        "dateStart": "2018-01-01T00:00:00Z",
        "dateEnd": "2018-02-01T00:00:00Z",
        "categories": [
          {
            "category":
            "https://divination.example.com/astrology/categories/health"
            "value": 70,
            "description": "Give a certain person or situation another
            try!"
          },
          {
            "category":
            "https://divination.example.com/astrology/categories/love"
            "value": 70,
            "description": "Give a certain person or situation another try!"
          },
          {
            "category":
            "https://divination.example.com/astrology/categories/finance"
            "value": 5,
            "description": "You've just realized that you don't have
            any cash on hand."
          }
        ]
      },
      {
        "dateStart": "2018-02-01T00:00:00Z",
        "dateEnd": "2018-03-01T00:00:00Z",
        "..."
      },
      "..."
    ]
    "events": [
      {
        "dateStart": "2018-01-15T03:20:00",
        "dateEnd": "2018-01-16T20:22:15",
        "description": "The planet of growth and good luck, Jupiter
        will make a harmonious connection with power planet Pluto,
        helping you connect with influential people",
        "recommendation": "Engage in networking during this time."
      },
      {
        "dateStart": "2018-03-22T00:12:40",
        "dateEnd": "2018-03-28T02:45:03",
        "description": "Communication planet Mercury enters your sign,
        which will find you in a busier and chattier mood.",
        "recommendation": "Take charge of work with your newfound
        energy."
      }
      "..."
    ]
  }
}
----

[#endpoint-report-interval-obj]
=== Report Interval Object

The `intervals` value of a report object contains a number of report
intervals -- each representing a non-overlapping period of the
selected interval length. When all of these intervals are put
together, the combined period **MUST** fully cover the requested
report target period.

An example interval object is shown below.

[source,json]
----
{
  "dateStart": "2018-01-01T00:00:00Z",
  "dateEnd": "2018-02-01T00:00:00Z",
  "categories": [
    {
      "category":
      "https://divination.example.com/astrology/categories/health"
      "value": 70,
      "description": "Give a certain person or situation another
      try!"
    },
    {
      "category":
      "https://divination.example.com/astrology/categories/love"
      "value": 70,
      "description": "Give a certain person or situation another try!"
    },
    {
      "category":
      "https://divination.example.com/astrology/categories/finance"
      "value": 5,
      "description": "You've just realized that you don't have
      any cash on hand."
    }
  ]
}
----

An interval object **MUST** contain the following members:

`dateStart`::
  (datetime, mandatory) This value specifies the start of the period
  which this interval object applies to.

`dateEnd`::
  (datetime, mandatory) This value specifies the end of the period
  which this interval object applies to.

In the given example, the `categories` key is an implementation
specific object that details heuristic results returned by the
selected algorithm. This **MAY** differ in different algorithms.


[#endpoint-report-event-obj]
=== Report Events Object

The `events` value of a report object contains a number of event
objects. Each event object represents an event relevant to the
calculation of fortune heuristics during a target report period. These
events **MAY** be of variable time lengths, and **MAY** be overlapping
amongst each other.

An event, for example, may represent when a significant event relevant
to the 

// Two event objects
[source,json]
----
{
  "dateStart": "2018-01-15T03:20:00",
  "dateEnd": "2018-01-16T20:22:15",
  "description": "The planet of growth and good luck, Jupiter will
  make a harmonious connection with power planet Pluto, helping you
  connect with influential people",
  "recommendation": "Engage in networking during this time."
},
{
  "dateStart": "2018-03-22T00:12:40",
  "dateEnd": "2018-03-28T02:45:03",
  "description": "Communication planet Mercury enters your sign,
  which will find you in a busier and chattier mood.",
  "recommendation": "Take charge of work with your newfound energy."
}
----

Similar to an interval object, an event object **MUST** contain the
following members:

`dateStart`::
  (datetime, mandatory) This value specifies the start of the period
  described by the event.

`dateEnd`::
  (datetime, mandatory) This value specifies the end of the period
  described by the event.

In the given example, the keys `description` and `recommendation`
are implementation-specific details. This **MAY** differ in different
algorithms.


[#endpoint-report-errors]
=== Report Generation Errors

This specification makes use of normal HTTP error codes.
Errors **MUST** be returned using the Problem JSON Structure as
accordance with <<RFC7807>>.

Examples of generation errors:

// TODO: change this to invalid request
422 Invalid Request::
  For example, a malformed date-time parameter, or an illogical input,
  such as when the subject's birthday occurs after the report target
  date period.

// TODO: change this to something else
422 Prediction Timeout::
  For example, in the case where the calculation is too complex to
  complete in a certain time period.

// TODO: change this to destroyed
404 Outcome does not exist::
  For example, when the algorithm determines that the subject will
  have deceased before the start of the requested target period.



[#security]
== Security Considerations

* TLS <<RFC5246>> and authenticated HTTP requests should be used to 
protect the DIVINE request and responses due to the personal nature
of information transmitted.

* A client **SHOULD** verify the identity of the server on every
request to prevent impersonation or man-in-the-middle attacks, as data
transmitted to and from the server is sensitive information, and at
times critical information to the user.

* Synchronization of client and server time **MUST** be
well-considered in the implementation of this specification. A
mismatch of client and server time **MAY** lead to algorithm
miscalculations that can cause mistaken choices of a user that depends
on the reliability of this system.



[#iana]
== IANA Considerations

=== Well-Known URI Registrations

This document defines a well-known URI using the registration
procedure and template from <<RFC5785,5.1 of>>.

==== "fortune" Well-Known URI Registration

URI suffix::  fortune

Change controller::  IETF

Specification document(s)::  This document

Related information::  N/A.


[bibliography]
== Normative References

//bibliography::norm[]
++++
include::references/normative/*.xml[]
++++

[bibliography]
== Informative References

//bibliography::info[]
++++
include::references/informative/*.xml[]
++++


[appendix]
== Acknowledgements

The authors thank the following individuals for their valuable
feedback on this specification and commend them for making fortune
heuristics more accessible to the general public.

